In [11]:
import pandas as pd
import numpy as np

df = pd.read_csv('./csv/2011전체데이터.csv', encoding='cp949')
df

            회사명  거래소코드     회계년도  이자보상배율(이자비용)  이자보상배율(이자비용)(IFRS연결)
0      (주)CMG제약  58820  2011/12          3.85                  3.53
1      (주)CMG제약  58820  2012/12         -7.45                 -7.75
2      (주)CMG제약  58820  2013/12          0.73                  0.70
3      (주)CMG제약  58820  2014/12          3.63                  3.60
4      (주)CMG제약  58820  2015/12        -32.20                -32.22
...         ...    ...      ...           ...                   ...
17776   흥아해운(주)   3280  2015/12          0.79                  1.02
17777   흥아해운(주)   3280  2016/12          0.04                  0.21
17778   흥아해운(주)   3280  2017/12         -0.61                 -0.42
17779   흥아해운(주)   3280  2018/12         -1.26                 -1.16
17780   흥아해운(주)   3280  2019/12         -0.58                 -0.55

[17781 rows x 5 columns]

In [13]:
df.isna().sum()
df = df.fillna(0)

In [14]:
df_1 = df[['회사명','거래소코드','회계년도','이자보상배율(이자비용)']]
df_2 = df[['회사명','거래소코드','회계년도','이자보상배율(이자비용)(IFRS연결)']]

In [15]:
for i in range(len(df_1)):
    if df_1.loc[i,'이자보상배율(이자비용)'] == 0: # 두개 다 결측치 인 경우 일단 2로...
        df_1.loc[i, '부실징후기업'] = 2
    elif df_1.loc[i,'이자보상배율(이자비용)'] < 1: # GAAP만 고려할 경우
        df_1.loc[i,'부실징후기업'] = 1
    elif df_1.loc[i,'이자보상배율(이자비용)'] > 1: # GAAP만 고려할 경우
        df_1.loc[i,'부실징후기업'] = 0

df_1 # 999999999는 일단 생각하지 않은 채로 진행합니다.

            회사명  거래소코드     회계년도  이자보상배율(이자비용)  부실징후기업
0      (주)CMG제약  58820  2011/12          3.85     0.0
1      (주)CMG제약  58820  2012/12         -7.45     1.0
2      (주)CMG제약  58820  2013/12          0.73     1.0
3      (주)CMG제약  58820  2014/12          3.63     0.0
4      (주)CMG제약  58820  2015/12        -32.20     1.0
...         ...    ...      ...           ...     ...
17776   흥아해운(주)   3280  2015/12          0.79     1.0
17777   흥아해운(주)   3280  2016/12          0.04     1.0
17778   흥아해운(주)   3280  2017/12         -0.61     1.0
17779   흥아해운(주)   3280  2018/12         -1.26     1.0
17780   흥아해운(주)   3280  2019/12         -0.58     1.0

[17781 rows x 5 columns]

In [17]:
for i in range(len(df_2)):
    if df_2.loc[i,'이자보상배율(이자비용)(IFRS연결)'] == 0: # 두개 다 결측치 인 경우 일단 2로...
        df_2.loc[i, '부실징후기업'] = 2
    elif df_2.loc[i,'이자보상배율(이자비용)(IFRS연결)'] < 1: # GAAP만 고려할 경우
        df_2.loc[i,'부실징후기업'] = 1
    elif df_2.loc[i,'이자보상배율(이자비용)(IFRS연결)'] > 1: # GAAP만 고려할 경우
        df_2.loc[i,'부실징후기업'] = 0

df_2 # 999999999는 일단 생각하지 않은 채로 진행합니다.

            회사명  거래소코드     회계년도  이자보상배율(이자비용)(IFRS연결)  부실징후기업
0      (주)CMG제약  58820  2011/12                  3.53     0.0
1      (주)CMG제약  58820  2012/12                 -7.75     1.0
2      (주)CMG제약  58820  2013/12                  0.70     1.0
3      (주)CMG제약  58820  2014/12                  3.60     0.0
4      (주)CMG제약  58820  2015/12                -32.22     1.0
...         ...    ...      ...                   ...     ...
17776   흥아해운(주)   3280  2015/12                  1.02     0.0
17777   흥아해운(주)   3280  2016/12                  0.21     1.0
17778   흥아해운(주)   3280  2017/12                 -0.42     1.0
17779   흥아해운(주)   3280  2018/12                 -1.16     1.0
17780   흥아해운(주)   3280  2019/12                 -0.55     1.0

[17781 rows x 5 columns]

In [18]:
for i in range(len(df_1)-2): # 3년 연속 부실징후가 1일 때
    if df_1.loc[i,'부실징후기업'] == 1:
        if df_1.loc[i+1,'부실징후기업'] == 1:
            if df_1.loc[i+2,'부실징후기업'] == 1:
                df_1.loc[i+2,"한계기업"] = 1
            else:
                df_1.loc[i+2,'한계기업'] = 0
        else:
            df_1.loc[i+1,'한계기업'] = 0
    else:
        df_1.loc[i,'한계기업'] = 0
df_1

            회사명  거래소코드     회계년도  이자보상배율(이자비용)  부실징후기업  한계기업
0      (주)CMG제약  58820  2011/12          3.85     0.0   0.0
1      (주)CMG제약  58820  2012/12         -7.45     1.0   NaN
2      (주)CMG제약  58820  2013/12          0.73     1.0   NaN
3      (주)CMG제약  58820  2014/12          3.63     0.0   0.0
4      (주)CMG제약  58820  2015/12        -32.20     1.0   NaN
...         ...    ...      ...           ...     ...   ...
17776   흥아해운(주)   3280  2015/12          0.79     1.0   NaN
17777   흥아해운(주)   3280  2016/12          0.04     1.0   1.0
17778   흥아해운(주)   3280  2017/12         -0.61     1.0   1.0
17779   흥아해운(주)   3280  2018/12         -1.26     1.0   1.0
17780   흥아해운(주)   3280  2019/12         -0.58     1.0   1.0

[17781 rows x 6 columns]

In [19]:
for i in range(len(df_2)-2): # 3년 연속 부실징후가 1일 때
    if df_2.loc[i,'부실징후기업'] == 1:
        if df_2.loc[i+1,'부실징후기업'] == 1:
            if df_2.loc[i+2,'부실징후기업'] == 1:
                df_2.loc[i+2,"한계기업"] = 1
            else:
                df_2.loc[i+2,'한계기업'] = 0
        else:
            df_2.loc[i+1,'한계기업'] = 0
    else:
        df_2.loc[i,'한계기업'] = 0
df_2

            회사명  거래소코드     회계년도  이자보상배율(이자비용)(IFRS연결)  부실징후기업  한계기업
0      (주)CMG제약  58820  2011/12                  3.53     0.0   0.0
1      (주)CMG제약  58820  2012/12                 -7.75     1.0   NaN
2      (주)CMG제약  58820  2013/12                  0.70     1.0   NaN
3      (주)CMG제약  58820  2014/12                  3.60     0.0   0.0
4      (주)CMG제약  58820  2015/12                -32.22     1.0   NaN
...         ...    ...      ...                   ...     ...   ...
17776   흥아해운(주)   3280  2015/12                  1.02     0.0   0.0
17777   흥아해운(주)   3280  2016/12                  0.21     1.0   NaN
17778   흥아해운(주)   3280  2017/12                 -0.42     1.0   NaN
17779   흥아해운(주)   3280  2018/12                 -1.16     1.0   1.0
17780   흥아해운(주)   3280  2019/12                 -0.55     1.0   1.0

[17781 rows x 6 columns]

In [23]:
a = df_1[df_1["한계기업"]==1]
a

            회사명  거래소코드     회계년도  이자보상배율(이자비용)  부실징후기업  한계기업
11     (주)DB하이텍    990  2013/12         -0.16     1.0   1.0
12     (주)DB하이텍    990  2014/12          0.67     1.0   1.0
27     (주)HJ중공업  97230  2011/12          0.22     1.0   1.0
28     (주)HJ중공업  97230  2012/12          0.17     1.0   1.0
29     (주)HJ중공업  97230  2013/12         -0.72     1.0   1.0
...         ...    ...      ...           ...     ...   ...
17742   휴림로봇(주)  90710  2014/12         -6.89     1.0   1.0
17777   흥아해운(주)   3280  2016/12          0.04     1.0   1.0
17778   흥아해운(주)   3280  2017/12         -0.61     1.0   1.0
17779   흥아해운(주)   3280  2018/12         -1.26     1.0   1.0
17780   흥아해운(주)   3280  2019/12         -0.58     1.0   1.0

[1682 rows x 6 columns]

In [24]:
a.drop_duplicates(['회사명'])

                회사명   거래소코드     회계년도  이자보상배율(이자비용)  부실징후기업  한계기업
11         (주)DB하이텍     990  2013/12         -0.16     1.0   1.0
27         (주)HJ중공업   97230  2011/12          0.22     1.0   1.0
83           (주)STX   11810  2013/12         -0.80     1.0   1.0
113      (주)강스템바이오텍  217730  2016/12        -18.89     1.0   1.0
133        (주)강원에너지  114190  2018/12          0.35     1.0   1.0
...             ...     ...      ...           ...     ...   ...
17519       현대로템(주)   64350  2019/12         -8.33     1.0   1.0
17532  현대바이오사이언스(주)   48410  2013/12        -18.28     1.0   1.0
17635       현우산업(주)   92300  2014/12         -2.26     1.0   1.0
17742       휴림로봇(주)   90710  2014/12         -6.89     1.0   1.0
17777       흥아해운(주)    3280  2016/12          0.04     1.0   1.0

[593 rows x 6 columns]

In [25]:
b = df_2[df_2["한계기업"]==1]
b

                회사명  거래소코드     회계년도  이자보상배율(이자비용)(IFRS연결)  부실징후기업  한계기업
11         (주)DB하이텍    990  2013/12                 -0.16     1.0   1.0
12         (주)DB하이텍    990  2014/12                  0.67     1.0   1.0
27         (주)HJ중공업  97230  2011/12                  0.55     1.0   1.0
28         (주)HJ중공업  97230  2012/12                  0.27     1.0   1.0
29         (주)HJ중공업  97230  2013/12                 -0.40     1.0   1.0
...             ...    ...      ...                   ...     ...   ...
17519       현대로템(주)  64350  2019/12                 -5.73     1.0   1.0
17532  현대바이오사이언스(주)  48410  2013/12                -16.73     1.0   1.0
17742       휴림로봇(주)  90710  2014/12                 -6.51     1.0   1.0
17779       흥아해운(주)   3280  2018/12                 -1.16     1.0   1.0
17780       흥아해운(주)   3280  2019/12                 -0.55     1.0   1.0

[1183 rows x 6 columns]

In [26]:
b.drop_duplicates(['회사명'])

                회사명  거래소코드     회계년도  이자보상배율(이자비용)(IFRS연결)  부실징후기업  한계기업
11         (주)DB하이텍    990  2013/12                 -0.16     1.0   1.0
27         (주)HJ중공업  97230  2011/12                  0.55     1.0   1.0
36         (주)MH에탄올  23150  2011/12                  0.12     1.0   1.0
84           (주)STX  11810  2014/12                  0.76     1.0   1.0
93         (주)TCC스틸   2710  2014/12                  0.02     1.0   1.0
...             ...    ...      ...                   ...     ...   ...
17457      해성옵틱스(주)  76610  2019/12                  0.31     1.0   1.0
17519       현대로템(주)  64350  2019/12                 -5.73     1.0   1.0
17532  현대바이오사이언스(주)  48410  2013/12                -16.73     1.0   1.0
17742       휴림로봇(주)  90710  2014/12                 -6.51     1.0   1.0
17779       흥아해운(주)   3280  2018/12                 -1.16     1.0   1.0

[436 rows x 6 columns]