In [137]:
import pandas as pd
import numpy as np

df = pd.read_csv('./csv/00_증가율1차.csv',encoding='cp949')
df = df.fillna(11111111.11)
df = df[['회사명','회계년도','유형자산증가율']]
df

            회사명  회계년도  유형자산증가율
0      (주)CMG제약  2011    -5.90
1      (주)CMG제약  2012    -4.12
2      (주)CMG제약  2013    16.09
3      (주)CMG제약  2014    74.30
4      (주)CMG제약  2015    -5.37
...         ...   ...      ...
15145   흥아해운(주)  2015    49.36
15146   흥아해운(주)  2016    38.84
15147   흥아해운(주)  2017   -16.50
15148   흥아해운(주)  2018   -12.07
15149   흥아해운(주)  2019   -51.51

[15150 rows x 3 columns]

In [111]:
# df[df['유형자산증가율']== 11111111.11]

In [112]:
# df[df['유형자산증가율']== 0]

In [113]:
dd = pd.read_csv('./유형자산.csv', encoding='cp949')
dd = dd.fillna(15975328.46)
dd

            회사명  거래소코드     회계년도  유형자산(*)(IFRS)(천원)  유형자산(*)(IFRS연결)(천원)
0      (주)CMG제약  58820  2011/12          9652599.0            9707759.0
1      (주)CMG제약  58820  2012/12          9264142.0            9307482.0
2      (주)CMG제약  58820  2013/12         10805092.0           10805092.0
3      (주)CMG제약  58820  2014/12         18833775.0           18833775.0
4      (주)CMG제약  58820  2015/12         17822468.0           17822468.0
...         ...    ...      ...                ...                  ...
15145   흥아해운(주)   3280  2015/12        479816639.0          483319774.0
15146   흥아해운(주)   3280  2016/12        667913303.0          671042170.0
15147   흥아해운(주)   3280  2017/12        557578439.0          560312598.0
15148   흥아해운(주)   3280  2018/12        490215607.0          492709259.0
15149   흥아해운(주)   3280  2019/12        237825418.0          238913893.0

[15150 rows x 5 columns]

In [96]:
# for i in range(len(dd)):
    
#     if dd.loc[i,'유형자산(*)(IFRS)(천원)'] != 15975328.46:
#         if dd.loc[i,'유형자산(*)(IFRS연결)(천원)'] != 15975328.46:
#             dd.loc[i,'유형자산'] = dd.loc[i,'유형자산(*)(IFRS연결)(천원)']
#         else:
#             dd.loc[i,'유형자산'] = dd.loc[i,'유형자산(*)(IFRS)(천원)']
#     else:
#         if dd.loc[i,'유형자산(*)(IFRS연결)(천원)'] != 15975328.46:
#             dd.loc[i,'유형자산'] = dd.loc[i,'유형자산(*)(IFRS연결)(천원)']
#         else:
#             dd.loc[i,'유형자산'] = 15151515.15
            
# dd

In [97]:
for i in range(len(dd)-1):
    if dd.loc[i,'회사명'] == dd.loc[i+1,'회사명']:
        if dd.loc[i,'유형자산(*)(IFRS)(천원)'] != 15975328.46:
            dd.loc[i,'0'] = (((dd.loc[i+1,'유형자산(*)(IFRS)(천원)'] / dd.loc[i,'유형자산(*)(IFRS)(천원)'])*100)-100).round(2)
        else:
            if dd.loc[i,'유형자산(*)(IFRS)(천원)'] == 15975328.46:
                continue
    elif dd.loc[i,'회사명'] != dd.loc[i+1,'회사명']:
        if dd.loc[i,'회사명'] == dd.loc[i-1,'회사명']:
            dd.loc[i,'0'] = (((dd.loc[i+1,'유형자산(*)(IFRS)(천원)'] / dd.loc[i,'유형자산(*)(IFRS)(천원)'])*100)-100).round(2)
        else:
            continue
dd

C:\Users\82104\AppData\Local\Temp\ipykernel_19672\2933163765.py:4: RuntimeWarning: invalid value encountered in double_scalars
  dd.loc[i,'0'] = (((dd.loc[i+1,'유형자산(*)(IFRS)(천원)'] / dd.loc[i,'유형자산(*)(IFRS)(천원)'])*100)-100).round(2)
C:\Users\82104\AppData\Local\Temp\ipykernel_19672\2933163765.py:4: RuntimeWarning: divide by zero encountered in double_scalars
  dd.loc[i,'0'] = (((dd.loc[i+1,'유형자산(*)(IFRS)(천원)'] / dd.loc[i,'유형자산(*)(IFRS)(천원)'])*100)-100).round(2)
C:\Users\82104\AppData\Local\Temp\ipykernel_19672\2933163765.py:10: RuntimeWarning: divide by zero encountered in double_scalars
  dd.loc[i,'0'] = (((dd.loc[i+1,'유형자산(*)(IFRS)(천원)'] / dd.loc[i,'유형자산(*)(IFRS)(천원)'])*100)-100).round(2)

            회사명  거래소코드     회계년도  유형자산(*)(IFRS)(천원)  유형자산(*)(IFRS연결)(천원)      0
0      (주)CMG제약  58820  2011/12          9652599.0            9707759.0  -4.02
1      (주)CMG제약  58820  2012/12          9264142.0            9307482.0  16.63
2      (주)CMG제약  58820  2013/12         10805092.0           10805092.0  74.30
3      (주)CMG제약  58820  2014/12         18833775.0           18833775.0  -5.37
4      (주)CMG제약  58820  2015/12         17822468.0           17822468.0  -5.14
...         ...    ...      ...                ...                  ...    ...
15145   흥아해운(주)   3280  2015/12        479816639.0          483319774.0  39.20
15146   흥아해운(주)   3280  2016/12        667913303.0          671042170.0 -16.52
15147   흥아해운(주)   3280  2017/12        557578439.0          560312598.0 -12.08
15148   흥아해운(주)   3280  2018/12        490215607.0          492709259.0 -51.49
15149   흥아해운(주)   3280  2019/12        237825418.0          238913893.0    NaN

[15150 rows x 6 columns]

In [98]:
for i in range(len(dd)-1):
    if dd.loc[i,'회사명'] == dd.loc[i+1,'회사명']:
        if dd.loc[i,'유형자산(*)(IFRS연결)(천원)'] != 15975328.46:
            dd.loc[i,'1'] = (((dd.loc[i+1,'유형자산(*)(IFRS연결)(천원)'] / dd.loc[i,'유형자산(*)(IFRS연결)(천원)'])*100)-100).round(2)
        else:
            continue
    elif dd.loc[i,'회사명'] != dd.loc[i+1,'회사명']:
        if dd.loc[i,'회사명'] == dd.loc[i-1,'회사명']:
            dd.loc[i,'0'] = (((dd.loc[i+1,'유형자산(*)(IFRS연결)(천원)'] / dd.loc[i,'유형자산(*)(IFRS연결)(천원)'])*100)-100).round(2)
        else:
            continue
dd

C:\Users\82104\AppData\Local\Temp\ipykernel_19672\3353419528.py:4: RuntimeWarning: divide by zero encountered in double_scalars
  dd.loc[i,'1'] = (((dd.loc[i+1,'유형자산(*)(IFRS연결)(천원)'] / dd.loc[i,'유형자산(*)(IFRS연결)(천원)'])*100)-100).round(2)

,회사명,거래소코드,회계년도,유형자산(*)(IFRS)(천원),유형자산(*)(IFRS연결)(천원),0,1
0,(주)CMG제약,58820,2011/12,9652599.0,9707759.0,-4.02,-4.12
1,(주)CMG제약,58820,2012/12,9264142.0,9307482.0,16.63,16.09
2,(주)CMG제약,58820,2013/12,10805092.0,10805092.0,74.30,74.30
3,(주)CMG제약,58820,2014/12,18833775.0,18833775.0,-5.37,-5.37
4,(주)CMG제약,58820,2015/12,17822468.0,17822468.0,-5.14,-5.14
...,...,...,...,...,...,...,...
15145,흥아해운(주),3280,2015/12,479816639.0,483319774.0,39.20,38.84
15146,흥아해운(주),3280,2016/12,667913303.0,671042170.0,-16.52,-16.50
15147,흥아해운(주),3280,2017/12,557578439.0,560312598.0,-12.08,-12.07
15148,흥아해운(주),3280,2018/12,490215607.0,492709259.0,-51.49,-51.51
15149,흥아해운(주),3280,2019/12,237825418.0,238913893.0,NaN,NaN

In [99]:
dd.to_csv('유형자산증가율.csv',encoding='cp949')

In [93]:
dd[60:85]

,회사명,거래소코드,회계년도,유형자산(*)(IFRS)(천원),유형자산(*)(IFRS연결)(천원),0,1
60,(주)SIMPAC,9160,2017/12,70402759.0,1.726598e+08,122.03,106.96
61,(주)SIMPAC,9160,2018/12,156312739.0,3.573314e+08,-2.12,-26.23
62,(주)SIMPAC,9160,2019/12,153003014.0,2.636082e+08,NaN,NaN
63,(주)SNT에너지,100840,2011/12,122586108.0,1.597533e+07,-0.24,NaN
64,(주)SNT에너지,100840,2012/12,122289502.0,1.597533e+07,-1.57,NaN
65,(주)SNT에너지,100840,2013/12,120367341.0,1.597533e+07,-0.25,NaN
66,(주)SNT에너지,100840,2014/12,120065551.0,1.597533e+07,-1.13,NaN
67,(주)SNT에너지,100840,2015/12,118714558.0,1.597533e+07,-0.48,NaN
68,(주)SNT에너지,100840,2016/12,118148046.0,1.597533e+07,-1.12,NaN
69,(주)SNT에너지,100840,2017/12,116825424.0,1.597533e+07,-0.94,NaN
70,(주)SNT에너지,100840,2018/12,115728393.0,1.597533e+07,0.47,NaN
71,(주)SNT에너지,100840,2019/12,116275557.0,1.232578e+08,NaN,NaN
72,(주)SNT홀딩스,36530,2011/12,150611.0,9.890389e+08,-33.43,-0.49
73,(주)SNT홀딩스,36530,2012/12,100263.0,9.841800e+08,-45.54,0.21
74,(주)SNT홀딩스,36530,2013/12,54602.0,9.862312e+08,38.12,-5.36
75,(주)SNT홀딩스,36530,2014/12,75419.0,9.333465e+08,-26.66,-0.54
76,(주)SNT홀딩스,36530,2015/12,55309.0,9.283159e+08,-35.54,-2.10
77,(주)SNT홀딩스,36530,2016/12,35654.0,9.088001e+08,-44.20,-3.08
78,(주)SNT홀딩스,36530,2017/12,19895.0,8.808438e+08,-85.48,-1.31
79,(주)SNT홀딩스,36530,2018/12,2888.0,8.692830e+08,1965.89,0.21
80,(주)SNT홀딩스,36530,2019/12,59663.0,8.711041e+08,NaN,NaN
81,(주)STX,11810,2011/12,72801000.0,8.184200e+08,-4.40,27.63
82,(주)STX,11810,2012/12,69598000.0,1.044547e+09,-10.70,-79.37
83,(주)STX,11810,2013/12,62152000.0,2.155100e+08,-8.10,-49.85
84,(주)STX,11810,2014/12,57120000.0,1.080800e+08,-5.96,-5.90

In [138]:
qw = pd.read_csv('./유형자산증가율.csv',encoding='cp949')
qw = qw.fillna(11111111.11)
qw = qw[['0','1']]
qw

                 0            1
0      11111111.11  11111111.11
1            -4.02        -4.12
2            16.63        16.09
3            74.30        74.30
4            -5.37        -5.37
...            ...          ...
15145        49.93        49.36
15146        39.20        38.84
15147       -16.52       -16.50
15148       -12.08       -12.07
15149       -51.49       -51.51

[15150 rows x 2 columns]

In [139]:
qq = pd.concat([df,qw],axis=1)
qq

            회사명  회계년도  유형자산증가율            0            1
0      (주)CMG제약  2011    -5.90  11111111.11  11111111.11
1      (주)CMG제약  2012    -4.12        -4.02        -4.12
2      (주)CMG제약  2013    16.09        16.63        16.09
3      (주)CMG제약  2014    74.30        74.30        74.30
4      (주)CMG제약  2015    -5.37        -5.37        -5.37
...         ...   ...      ...          ...          ...
15145   흥아해운(주)  2015    49.36        49.93        49.36
15146   흥아해운(주)  2016    38.84        39.20        38.84
15147   흥아해운(주)  2017   -16.50       -16.52       -16.50
15148   흥아해운(주)  2018   -12.07       -12.08       -12.07
15149   흥아해운(주)  2019   -51.51       -51.49       -51.51

[15150 rows x 5 columns]

In [140]:
for i in range(len(qq)):
    if qq.loc[i,'유형자산증가율'] == 0:
        if qq.loc[i,'0'] != 15975328.46:
            if qq.loc[i,'1'] != 15975328.46:
                qq.loc[i,'유형자산증가율'] = qq.loc[i,'1']
            else:
                qq.loc[i,'유형자산증가율'] = qq.loc[i,'0']
        else:
            if qq.loc[i,'1'] != 15975328.46:
                qq.loc[i,'유형자산증가율'] = qq.loc[i,'1']
            else:
                qq.loc[i,'유형자산증가율'] = 1254789.63
        if qq.loc[i,'1'] == 0:
            qq.loc[i,'유형자산증가율'] = qq.loc[i,'0']
        if qq.loc[i,'1'] == 15975328.46:
            qq.loc[i,'유형자산증가율'] = 15975328.46
        
qq

            회사명  회계년도  유형자산증가율            0            1
0      (주)CMG제약  2011    -5.90  11111111.11  11111111.11
1      (주)CMG제약  2012    -4.12        -4.02        -4.12
2      (주)CMG제약  2013    16.09        16.63        16.09
3      (주)CMG제약  2014    74.30        74.30        74.30
4      (주)CMG제약  2015    -5.37        -5.37        -5.37
...         ...   ...      ...          ...          ...
15145   흥아해운(주)  2015    49.36        49.93        49.36
15146   흥아해운(주)  2016    38.84        39.20        38.84
15147   흥아해운(주)  2017   -16.50       -16.52       -16.50
15148   흥아해운(주)  2018   -12.07       -12.08       -12.07
15149   흥아해운(주)  2019   -51.51       -51.49       -51.51

[15150 rows x 5 columns]