In [168]:
import pandas as pd
import numpy as np

df = pd.read_csv('./csv/00_증가율1차.csv',encoding='cp949')
df = df.fillna(11111111.11)
# df['회계년도'] = pd.to_datetime(df['회계년도'], format='%Y').dt.strftime('%b-%d')
df

,회사명,거래소코드,회계년도,총자본증가율,유형자산증가율,유동자산증가율,재고자산증가율,자기자본증가율,매출액증가율,정상영업이익증가율,...,유형자산회전율,순운전자본회전률,운전자본회전률,노동장비율,기계장비율,자본집약도,총자본투자효율,설비투자효율,기계투자효율,부가가치율
0,(주)CMG제약,58820,2011,1.98,-5.90,17.64,-1.43,-2.02,56.40,0.00,...,1.77,0.86,0.00,71.32,19.75,204.06,12.72,35.86,1.285100e+02,19.56
1,(주)CMG제약,58820,2012,109.15,-4.12,207.08,7.73,75.17,-8.43,0.00,...,1.71,0.42,0.00,69.14,18.64,425.29,0.47,2.89,1.067000e+01,1.66
2,(주)CMG제약,58820,2013,-2.09,16.09,-18.89,56.29,55.10,25.51,0.00,...,2.03,0.42,0.79,66.01,17.77,411.48,12.51,77.91,2.894000e+02,34.29
3,(주)CMG제약,58820,2014,3.86,74.30,-25.93,6.37,0.01,11.52,-46.64,...,1.54,0.56,0.74,113.90,32.60,354.43,12.16,37.80,1.320600e+02,31.04
4,(주)CMG제약,58820,2015,-2.64,-5.37,-7.17,11.04,-4.48,18.85,0.00,...,1.48,0.75,0.60,114.25,30.43,362.77,7.63,24.21,9.092000e+01,15.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15145,흥아해운(주),3280,2015,21.93,49.36,-11.18,-12.92,3.39,2.42,-42.68,...,2.09,2.15,0.01,589.65,0.00,948.60,13.11,21.49,3.459744e+09,12.28
15146,흥아해운(주),3280,2016,21.08,38.84,-25.08,56.39,11.22,-1.58,-263.29,...,1.44,2.19,0.02,703.55,0.00,1000.62,10.98,15.81,3.509713e+09,12.66
15147,흥아해운(주),3280,2017,-11.43,-16.50,13.29,11.18,-39.28,0.56,0.00,...,1.36,2.09,0.02,0.00,0.00,0.00,5.43,8.35,1.535742e+09,5.51
15148,흥아해운(주),3280,2018,-5.33,-12.07,-6.33,-5.85,-37.42,-9.87,0.00,...,1.43,1.75,0.02,0.00,0.00,0.00,4.24,6.91,1.135163e+09,4.52
15149,흥아해운(주),3280,2019,-46.38,-51.51,-13.42,-58.98,-57.73,-86.45,0.00,...,0.28,0.28,0.10,0.00,0.00,0.00,3.10,5.59,4.455416e+08,13.08

In [2]:
# df[df['유형자산증가율']== 11111111.11]

In [3]:
# df[df['유형자산증가율']== 0]

In [4]:
dd = pd.read_csv('./유형자산.csv', encoding='cp949')
dd = dd.fillna(15975328.46)
dd

            회사명  거래소코드     회계년도  유형자산(*)(IFRS)(천원)  유형자산(*)(IFRS연결)(천원)
0      (주)CMG제약  58820  2011/12          9652599.0            9707759.0
1      (주)CMG제약  58820  2012/12          9264142.0            9307482.0
2      (주)CMG제약  58820  2013/12         10805092.0           10805092.0
3      (주)CMG제약  58820  2014/12         18833775.0           18833775.0
4      (주)CMG제약  58820  2015/12         17822468.0           17822468.0
...         ...    ...      ...                ...                  ...
15145   흥아해운(주)   3280  2015/12        479816639.0          483319774.0
15146   흥아해운(주)   3280  2016/12        667913303.0          671042170.0
15147   흥아해운(주)   3280  2017/12        557578439.0          560312598.0
15148   흥아해운(주)   3280  2018/12        490215607.0          492709259.0
15149   흥아해운(주)   3280  2019/12        237825418.0          238913893.0

[15150 rows x 5 columns]

In [5]:
# for i in range(len(dd)):
    
#     if dd.loc[i,'유형자산(*)(IFRS)(천원)'] != 15975328.46:
#         if dd.loc[i,'유형자산(*)(IFRS연결)(천원)'] != 15975328.46:
#             dd.loc[i,'유형자산'] = dd.loc[i,'유형자산(*)(IFRS연결)(천원)']
#         else:
#             dd.loc[i,'유형자산'] = dd.loc[i,'유형자산(*)(IFRS)(천원)']
#     else:
#         if dd.loc[i,'유형자산(*)(IFRS연결)(천원)'] != 15975328.46:
#             dd.loc[i,'유형자산'] = dd.loc[i,'유형자산(*)(IFRS연결)(천원)']
#         else:
#             dd.loc[i,'유형자산'] = 15151515.15
            
# dd

In [6]:
for i in range(len(dd)-1):
    if dd.loc[i,'회사명'] == dd.loc[i+1,'회사명']:
        if dd.loc[i,'유형자산(*)(IFRS)(천원)'] != 15975328.46:
            dd.loc[i,'0'] = (((dd.loc[i+1,'유형자산(*)(IFRS)(천원)'] / dd.loc[i,'유형자산(*)(IFRS)(천원)'])*100)-100).round(2)
        else:
            if dd.loc[i,'유형자산(*)(IFRS)(천원)'] == 15975328.46:
                continue
    elif dd.loc[i,'회사명'] != dd.loc[i+1,'회사명']:
        if dd.loc[i,'회사명'] == dd.loc[i-1,'회사명']:
            dd.loc[i,'0'] = (((dd.loc[i+1,'유형자산(*)(IFRS)(천원)'] / dd.loc[i,'유형자산(*)(IFRS)(천원)'])*100)-100).round(2)
        else:
            continue
dd

C:\Users\82104\AppData\Local\Temp\ipykernel_2668\2933163765.py:4: RuntimeWarning: invalid value encountered in double_scalars
  dd.loc[i,'0'] = (((dd.loc[i+1,'유형자산(*)(IFRS)(천원)'] / dd.loc[i,'유형자산(*)(IFRS)(천원)'])*100)-100).round(2)
C:\Users\82104\AppData\Local\Temp\ipykernel_2668\2933163765.py:4: RuntimeWarning: divide by zero encountered in double_scalars
  dd.loc[i,'0'] = (((dd.loc[i+1,'유형자산(*)(IFRS)(천원)'] / dd.loc[i,'유형자산(*)(IFRS)(천원)'])*100)-100).round(2)
C:\Users\82104\AppData\Local\Temp\ipykernel_2668\2933163765.py:10: RuntimeWarning: divide by zero encountered in double_scalars
  dd.loc[i,'0'] = (((dd.loc[i+1,'유형자산(*)(IFRS)(천원)'] / dd.loc[i,'유형자산(*)(IFRS)(천원)'])*100)-100).round(2)

            회사명  거래소코드     회계년도  유형자산(*)(IFRS)(천원)  유형자산(*)(IFRS연결)(천원)      0
0      (주)CMG제약  58820  2011/12          9652599.0            9707759.0  -4.02
1      (주)CMG제약  58820  2012/12          9264142.0            9307482.0  16.63
2      (주)CMG제약  58820  2013/12         10805092.0           10805092.0  74.30
3      (주)CMG제약  58820  2014/12         18833775.0           18833775.0  -5.37
4      (주)CMG제약  58820  2015/12         17822468.0           17822468.0  -5.14
...         ...    ...      ...                ...                  ...    ...
15145   흥아해운(주)   3280  2015/12        479816639.0          483319774.0  39.20
15146   흥아해운(주)   3280  2016/12        667913303.0          671042170.0 -16.52
15147   흥아해운(주)   3280  2017/12        557578439.0          560312598.0 -12.08
15148   흥아해운(주)   3280  2018/12        490215607.0          492709259.0 -51.49
15149   흥아해운(주)   3280  2019/12        237825418.0          238913893.0    NaN

[15150 rows x 6 columns]

In [7]:
for i in range(len(dd)-1):
    if dd.loc[i,'회사명'] == dd.loc[i+1,'회사명']:
        if dd.loc[i,'유형자산(*)(IFRS연결)(천원)'] != 15975328.46:
            dd.loc[i,'1'] = (((dd.loc[i+1,'유형자산(*)(IFRS연결)(천원)'] / dd.loc[i,'유형자산(*)(IFRS연결)(천원)'])*100)-100).round(2)
        else:
            continue
    elif dd.loc[i,'회사명'] != dd.loc[i+1,'회사명']:
        if dd.loc[i,'회사명'] == dd.loc[i-1,'회사명']:
            dd.loc[i,'0'] = (((dd.loc[i+1,'유형자산(*)(IFRS연결)(천원)'] / dd.loc[i,'유형자산(*)(IFRS연결)(천원)'])*100)-100).round(2)
        else:
            continue
dd

C:\Users\82104\AppData\Local\Temp\ipykernel_2668\3353419528.py:4: RuntimeWarning: divide by zero encountered in double_scalars
  dd.loc[i,'1'] = (((dd.loc[i+1,'유형자산(*)(IFRS연결)(천원)'] / dd.loc[i,'유형자산(*)(IFRS연결)(천원)'])*100)-100).round(2)

,회사명,거래소코드,회계년도,유형자산(*)(IFRS)(천원),유형자산(*)(IFRS연결)(천원),0,1
0,(주)CMG제약,58820,2011/12,9652599.0,9707759.0,-4.02,-4.12
1,(주)CMG제약,58820,2012/12,9264142.0,9307482.0,16.63,16.09
2,(주)CMG제약,58820,2013/12,10805092.0,10805092.0,74.30,74.30
3,(주)CMG제약,58820,2014/12,18833775.0,18833775.0,-5.37,-5.37
4,(주)CMG제약,58820,2015/12,17822468.0,17822468.0,-5.14,-5.14
...,...,...,...,...,...,...,...
15145,흥아해운(주),3280,2015/12,479816639.0,483319774.0,39.20,38.84
15146,흥아해운(주),3280,2016/12,667913303.0,671042170.0,-16.52,-16.50
15147,흥아해운(주),3280,2017/12,557578439.0,560312598.0,-12.08,-12.07
15148,흥아해운(주),3280,2018/12,490215607.0,492709259.0,-51.49,-51.51
15149,흥아해운(주),3280,2019/12,237825418.0,238913893.0,NaN,NaN

In [8]:
# dd.to_csv('유형자산증가율.csv',encoding='cp949')

In [9]:
dd[60:85]

,회사명,거래소코드,회계년도,유형자산(*)(IFRS)(천원),유형자산(*)(IFRS연결)(천원),0,1
60,(주)SIMPAC,9160,2017/12,70402759.0,1.726598e+08,122.03,106.96
61,(주)SIMPAC,9160,2018/12,156312739.0,3.573314e+08,-2.12,-26.23
62,(주)SIMPAC,9160,2019/12,153003014.0,2.636082e+08,-93.94,NaN
63,(주)SNT에너지,100840,2011/12,122586108.0,1.597533e+07,-0.24,NaN
64,(주)SNT에너지,100840,2012/12,122289502.0,1.597533e+07,-1.57,NaN
65,(주)SNT에너지,100840,2013/12,120367341.0,1.597533e+07,-0.25,NaN
66,(주)SNT에너지,100840,2014/12,120065551.0,1.597533e+07,-1.13,NaN
67,(주)SNT에너지,100840,2015/12,118714558.0,1.597533e+07,-0.48,NaN
68,(주)SNT에너지,100840,2016/12,118148046.0,1.597533e+07,-1.12,NaN
69,(주)SNT에너지,100840,2017/12,116825424.0,1.597533e+07,-0.94,NaN
70,(주)SNT에너지,100840,2018/12,115728393.0,1.597533e+07,0.47,NaN
71,(주)SNT에너지,100840,2019/12,116275557.0,1.232578e+08,702.41,NaN
72,(주)SNT홀딩스,36530,2011/12,150611.0,9.890389e+08,-33.43,-0.49
73,(주)SNT홀딩스,36530,2012/12,100263.0,9.841800e+08,-45.54,0.21
74,(주)SNT홀딩스,36530,2013/12,54602.0,9.862312e+08,38.12,-5.36
75,(주)SNT홀딩스,36530,2014/12,75419.0,9.333465e+08,-26.66,-0.54
76,(주)SNT홀딩스,36530,2015/12,55309.0,9.283159e+08,-35.54,-2.10
77,(주)SNT홀딩스,36530,2016/12,35654.0,9.088001e+08,-44.20,-3.08
78,(주)SNT홀딩스,36530,2017/12,19895.0,8.808438e+08,-85.48,-1.31
79,(주)SNT홀딩스,36530,2018/12,2888.0,8.692830e+08,1965.89,0.21
80,(주)SNT홀딩스,36530,2019/12,59663.0,8.711041e+08,-6.05,NaN
81,(주)STX,11810,2011/12,72801000.0,8.184200e+08,-4.40,27.63
82,(주)STX,11810,2012/12,69598000.0,1.044547e+09,-10.70,-79.37
83,(주)STX,11810,2013/12,62152000.0,2.155100e+08,-8.10,-49.85
84,(주)STX,11810,2014/12,57120000.0,1.080800e+08,-5.96,-5.90

In [10]:
qw = pd.read_csv('./유형자산증가율.csv',encoding='cp949')
qw = qw.fillna(11111111.11)
qw = qw[['0','1']]
qw

                 0            1
0      11111111.11  11111111.11
1            -4.02        -4.12
2            16.63        16.09
3            74.30        74.30
4            -5.37        -5.37
...            ...          ...
15145        49.93        49.36
15146        39.20        38.84
15147       -16.52       -16.50
15148       -12.08       -12.07
15149       -51.49       -51.51

[15150 rows x 2 columns]

In [11]:
qq = pd.concat([df,qw],axis=1)
qq

            회사명  회계년도  유형자산증가율            0            1
0      (주)CMG제약  2011    -5.90  11111111.11  11111111.11
1      (주)CMG제약  2012    -4.12        -4.02        -4.12
2      (주)CMG제약  2013    16.09        16.63        16.09
3      (주)CMG제약  2014    74.30        74.30        74.30
4      (주)CMG제약  2015    -5.37        -5.37        -5.37
...         ...   ...      ...          ...          ...
15145   흥아해운(주)  2015    49.36        49.93        49.36
15146   흥아해운(주)  2016    38.84        39.20        38.84
15147   흥아해운(주)  2017   -16.50       -16.52       -16.50
15148   흥아해운(주)  2018   -12.07       -12.08       -12.07
15149   흥아해운(주)  2019   -51.51       -51.49       -51.51

[15150 rows x 5 columns]

In [19]:
for i in range(len(qq)):
    if qq.loc[i,'유형자산증가율'] == 0:
        if qq.loc[i,'0'] != 11111111.11:
            if qq.loc[i,'1'] != 11111111.11:
                qq.loc[i,'유형자산증가율'] = qq.loc[i,'1']
            else:
                qq.loc[i,'유형자산증가율'] = qq.loc[i,'0']
        else:
            if qq.loc[i,'1'] != 11111111.11:
                qq.loc[i,'유형자산증가율'] = qq.loc[i,'1']
            else:
                qq.loc[i,'유형자산증가율'] = 1254789.63
        if qq.loc[i,'1'] == 0:
            qq.loc[i,'유형자산증가율'] = qq.loc[i,'0']
        if qq.loc[i,'1'] == 11111111.11:
            qq.loc[i,'유형자산증가율'] = 11111111.11
    if qq.loc[i,'유형자산증가율'] == 11111111.11:
        if qq.loc[i,'1'] != 11111111.11:
            if qq.loc[i,'0'] != 11111111.11:
                qq.loc[i,'유형자산증가율'] = qq.loc[i,'1']
            else:
                qq.loc[i,'유형자산증가율'] = qq.loc[i,'1']
        if qq.loc[i,'1'] == 11111111.11:
            if qq.loc[i,'0'] != 11111111.11:
                qq.loc[i,'유형자산증가율'] = qq.loc[i,'0']
            else:
                qq.loc[i,'유형자산증가율'] = 1254789.63
        
qq

            회사명  회계년도  유형자산증가율            0            1
0      (주)CMG제약  2011    -5.90  11111111.11  11111111.11
1      (주)CMG제약  2012    -4.12        -4.02        -4.12
2      (주)CMG제약  2013    16.09        16.63        16.09
3      (주)CMG제약  2014    74.30        74.30        74.30
4      (주)CMG제약  2015    -5.37        -5.37        -5.37
...         ...   ...      ...          ...          ...
15145   흥아해운(주)  2015    49.36        49.93        49.36
15146   흥아해운(주)  2016    38.84        39.20        38.84
15147   흥아해운(주)  2017   -16.50       -16.52       -16.50
15148   흥아해운(주)  2018   -12.07       -12.08       -12.07
15149   흥아해운(주)  2019   -51.51       -51.49       -51.51

[15150 rows x 5 columns]

In [20]:
qq[qq['유형자산증가율']==11111111.11]

Empty DataFrame
Columns: [회사명, 회계년도, 유형자산증가율, 0, 1]
Index: []

In [21]:
# qq.to_csv('유형자산증가율.csv',encoding='cp949')

In [23]:
mm = pd.read_csv('총자산.csv',encoding='cp949')
mm = mm.fillna(11111111.11)
mm

            회사명  거래소코드     회계년도  자산(*)(IFRS)(천원)  자산(*)(IFRS연결)(천원)
0      (주)CMG제약  58820  2011/12       27548539.0         27305198.0
1      (주)CMG제약  58820  2012/12       56988604.0         57108035.0
2      (주)CMG제약  58820  2013/12       55961620.0         55912563.0
3      (주)CMG제약  58820  2014/12       58127098.0         58068326.0
4      (주)CMG제약  58820  2015/12       56591972.0         56532821.0
...         ...    ...      ...              ...                ...
15145   흥아해운(주)   3280  2015/12      771212062.0        791640802.0
15146   흥아해운(주)   3280  2016/12      942586770.0        958532259.0
15147   흥아해운(주)   3280  2017/12      834107402.0        848958520.0
15148   흥아해운(주)   3280  2018/12      782787041.0        803698457.0
15149   흥아해운(주)   3280  2019/12      386550839.0        430962722.0

[15150 rows x 5 columns]

In [24]:
for i in range(len(mm)-1):
    if mm.loc[i,'회사명'] == mm.loc[i+1,'회사명']:
        if mm.loc[i,'자산(*)(IFRS)(천원)'] != 11111111.11:
            mm.loc[i,'0'] = (((mm.loc[i+1,'자산(*)(IFRS)(천원)'] - mm.loc[i,'자산(*)(IFRS)(천원)'])/mm.loc[i,'자산(*)(IFRS)(천원)'])*100).round(2)
        else:
            if mm.loc[i,'자산(*)(IFRS)(천원)'] == 11111111.11:
                continue
    elif mm.loc[i,'회사명'] != mm.loc[i+1,'회사명']:
        if mm.loc[i,'회사명'] == mm.loc[i-1,'회사명']:
            mm.loc[i,'0'] = (((mm.loc[i+1,'자산(*)(IFRS)(천원)'] - mm.loc[i,'자산(*)(IFRS)(천원)'])/mm.loc[i,'자산(*)(IFRS)(천원)'])*100).round(2)
        else:
            continue
mm

            회사명  거래소코드     회계년도  자산(*)(IFRS)(천원)  자산(*)(IFRS연결)(천원)       0
0      (주)CMG제약  58820  2011/12       27548539.0         27305198.0  106.87
1      (주)CMG제약  58820  2012/12       56988604.0         57108035.0   -1.80
2      (주)CMG제약  58820  2013/12       55961620.0         55912563.0    3.87
3      (주)CMG제약  58820  2014/12       58127098.0         58068326.0   -2.64
4      (주)CMG제약  58820  2015/12       56591972.0         56532821.0   96.11
...         ...    ...      ...              ...                ...     ...
15145   흥아해운(주)   3280  2015/12      771212062.0        791640802.0   22.22
15146   흥아해운(주)   3280  2016/12      942586770.0        958532259.0  -11.51
15147   흥아해운(주)   3280  2017/12      834107402.0        848958520.0   -6.15
15148   흥아해운(주)   3280  2018/12      782787041.0        803698457.0  -50.62
15149   흥아해운(주)   3280  2019/12      386550839.0        430962722.0     NaN

[15150 rows x 6 columns]

In [25]:
for i in range(len(mm)-1):
    if mm.loc[i,'회사명'] == mm.loc[i+1,'회사명']:
        if mm.loc[i,'자산(*)(IFRS연결)(천원)'] != 11111111.11:
            mm.loc[i,'1'] = (((mm.loc[i+1,'자산(*)(IFRS연결)(천원)'] - mm.loc[i,'자산(*)(IFRS연결)(천원)'])/mm.loc[i,'자산(*)(IFRS연결)(천원)'])*100).round(2)
        else:
            if mm.loc[i,'자산(*)(IFRS연결)(천원)'] == 11111111.11:
                continue
    elif mm.loc[i,'회사명'] != mm.loc[i+1,'회사명']:
        if mm.loc[i,'회사명'] == mm.loc[i-1,'회사명']:
            mm.loc[i,'1'] = (((mm.loc[i+1,'자산(*)(IFRS연결)(천원)'] - mm.loc[i,'자산(*)(IFRS연결)(천원)'])/mm.loc[i,'자산(*)(IFRS연결)(천원)'])*100).round(2)
        else:
            continue
mm

,회사명,거래소코드,회계년도,자산(*)(IFRS)(천원),자산(*)(IFRS연결)(천원),0,1
0,(주)CMG제약,58820,2011/12,27548539.0,27305198.0,106.87,109.15
1,(주)CMG제약,58820,2012/12,56988604.0,57108035.0,-1.80,-2.09
2,(주)CMG제약,58820,2013/12,55961620.0,55912563.0,3.87,3.86
3,(주)CMG제약,58820,2014/12,58127098.0,58068326.0,-2.64,-2.64
4,(주)CMG제약,58820,2015/12,56591972.0,56532821.0,96.11,96.31
...,...,...,...,...,...,...,...
15145,흥아해운(주),3280,2015/12,771212062.0,791640802.0,22.22,21.08
15146,흥아해운(주),3280,2016/12,942586770.0,958532259.0,-11.51,-11.43
15147,흥아해운(주),3280,2017/12,834107402.0,848958520.0,-6.15,-5.33
15148,흥아해운(주),3280,2018/12,782787041.0,803698457.0,-50.62,-46.38
15149,흥아해운(주),3280,2019/12,386550839.0,430962722.0,NaN,NaN

In [31]:
mm = pd.read_csv('총자산비율.csv',encoding='cp949')
mm = mm.fillna(11111111.11)
mm

,Unnamed: 0,회사명,거래소코드,회계년도,자산(*)(IFRS)(천원),자산(*)(IFRS연결)(천원),0,1
0,0,(주)CMG제약,58820,Dec-11,27548539.0,27305198.0,11111111.11,11111111.11
1,1,(주)CMG제약,58820,Dec-12,56988604.0,57108035.0,106.87,109.15
2,2,(주)CMG제약,58820,Dec-13,55961620.0,55912563.0,-1.80,-2.09
3,3,(주)CMG제약,58820,Dec-14,58127098.0,58068326.0,3.87,3.86
4,4,(주)CMG제약,58820,Dec-15,56591972.0,56532821.0,-2.64,-2.64
...,...,...,...,...,...,...,...,...
15145,15145,흥아해운(주),3280,Dec-15,771212062.0,791640802.0,22.84,21.93
15146,15146,흥아해운(주),3280,Dec-16,942586770.0,958532259.0,22.22,21.08
15147,15147,흥아해운(주),3280,Dec-17,834107402.0,848958520.0,-11.51,-11.43
15148,15148,흥아해운(주),3280,Dec-18,782787041.0,803698457.0,-6.15,-5.33
15149,15149,흥아해운(주),3280,Dec-19,386550839.0,430962722.0,-50.62,-46.38

In [33]:
m1 = pd.concat([df[['회사명','총자본증가율']],mm[['0','1']]],axis=1)
m1

            회사명  총자본증가율            0            1
0      (주)CMG제약    1.98  11111111.11  11111111.11
1      (주)CMG제약  109.15       106.87       109.15
2      (주)CMG제약   -2.09        -1.80        -2.09
3      (주)CMG제약    3.86         3.87         3.86
4      (주)CMG제약   -2.64        -2.64        -2.64
...         ...     ...          ...          ...
15145   흥아해운(주)   21.93        22.84        21.93
15146   흥아해운(주)   21.08        22.22        21.08
15147   흥아해운(주)  -11.43       -11.51       -11.43
15148   흥아해운(주)   -5.33        -6.15        -5.33
15149   흥아해운(주)  -46.38       -50.62       -46.38

[15150 rows x 4 columns]

In [34]:
for i in range(len(m1)):
    if m1.loc[i,'총자본증가율'] == 0:
        if m1.loc[i,'0'] != 11111111.11:
            if m1.loc[i,'1'] != 11111111.11:
                m1.loc[i,'총자본증가율'] = m1.loc[i,'1']
            else:
                m1.loc[i,'총자본증가율'] = m1.loc[i,'0']
        else:
            if m1.loc[i,'1'] != 11111111.11:
                m1.loc[i,'총자본증가율'] = m1.loc[i,'1']
            else:
                m1.loc[i,'총자본증가율'] = 1254789.63
        if m1.loc[i,'1'] == 0:
            m1.loc[i,'총자본증가율'] = m1.loc[i,'0']
        if m1.loc[i,'1'] == 11111111.11:
            m1.loc[i,'총자본증가율'] = 11111111.11
    if m1.loc[i,'총자본증가율'] == 11111111.11:
        if m1.loc[i,'1'] != 11111111.11:
            if m1.loc[i,'0'] != 11111111.11:
                m1.loc[i,'총자본증가율'] = m1.loc[i,'1']
            else:
                m1.loc[i,'총자본증가율'] = m1.loc[i,'1']
        if m1.loc[i,'1'] == 11111111.11:
            if m1.loc[i,'0'] != 11111111.11:
                m1.loc[i,'총자본증가율'] = m1.loc[i,'0']
            else:
                m1.loc[i,'총자본증가율'] = 1254789.63
        
m1

            회사명  총자본증가율            0            1
0      (주)CMG제약    1.98  11111111.11  11111111.11
1      (주)CMG제약  109.15       106.87       109.15
2      (주)CMG제약   -2.09        -1.80        -2.09
3      (주)CMG제약    3.86         3.87         3.86
4      (주)CMG제약   -2.64        -2.64        -2.64
...         ...     ...          ...          ...
15145   흥아해운(주)   21.93        22.84        21.93
15146   흥아해운(주)   21.08        22.22        21.08
15147   흥아해운(주)  -11.43       -11.51       -11.43
15148   흥아해운(주)   -5.33        -6.15        -5.33
15149   흥아해운(주)  -46.38       -50.62       -46.38

[15150 rows x 4 columns]

In [35]:
# m1.to_csv('m1.csv',encoding='cp949')

In [37]:
q1 = pd.read_csv('재고,유동.csv',encoding='cp949')
q1 = q1.fillna(11111111.11)
q1

,회사명,거래소코드,회계년도,유동자산(*)(IFRS)(천원),유동자산(*)(IFRS연결)(천원),재고자산(*)(IFRS)(천원),재고자산(*)(IFRS연결)(천원)
0,(주)CMG제약,58820,2011/12,15264885.0,15341167.0,2743103.0,2743103.0
1,(주)CMG제약,58820,2012/12,47073443.0,47109213.0,2955172.0,2955172.0
2,(주)CMG제약,58820,2013/12,38258866.0,38209699.0,4618718.0,4618718.0
3,(주)CMG제약,58820,2014/12,28359823.0,28300941.0,4913103.0,4913103.0
4,(주)CMG제약,58820,2015/12,26330765.0,26271614.0,5455617.0,5455617.0
...,...,...,...,...,...,...,...
15145,흥아해운(주),3280,2015/12,124478864.0,136280257.0,11488626.0,11488626.0
15146,흥아해운(주),3280,2016/12,90973953.0,102103828.0,17967554.0,17967554.0
15147,흥아해운(주),3280,2017/12,105819304.0,115675013.0,19976759.0,19976759.0
15148,흥아해운(주),3280,2018/12,103181415.0,108354984.0,18794127.0,18807927.0
15149,흥아해운(주),3280,2019/12,61182850.0,93810124.0,7544969.0,7715548.0

In [39]:
for i in range(len(q1)-1):
    if q1.loc[i,'회사명'] == q1.loc[i+1,'회사명']:
        if q1.loc[i,'유동자산(*)(IFRS연결)(천원)'] != 11111111.11:
            q1.loc[i,'1'] = (((q1.loc[i+1,'유동자산(*)(IFRS연결)(천원)'] - q1.loc[i,'유동자산(*)(IFRS연결)(천원)'])/q1.loc[i,'유동자산(*)(IFRS연결)(천원)'])*100).round(2)
        else:
            if q1.loc[i,'유동자산(*)(IFRS연결)(천원)'] == 11111111.11:
                continue
    elif q1.loc[i,'회사명'] != q1.loc[i+1,'회사명']:
        if q1.loc[i,'회사명'] == q1.loc[i-1,'회사명']:
            q1.loc[i,'1'] = (((q1.loc[i+1,'유동자산(*)(IFRS연결)(천원)'] - q1.loc[i,'유동자산(*)(IFRS연결)(천원)'])/q1.loc[i,'유동자산(*)(IFRS연결)(천원)'])*100).round(2)
        else:
            continue
q1

,회사명,거래소코드,회계년도,유동자산(*)(IFRS)(천원),유동자산(*)(IFRS연결)(천원),재고자산(*)(IFRS)(천원),재고자산(*)(IFRS연결)(천원),0,1
0,(주)CMG제약,58820,2011/12,15264885.0,15341167.0,2743103.0,2743103.0,208.38,207.08
1,(주)CMG제약,58820,2012/12,47073443.0,47109213.0,2955172.0,2955172.0,-18.73,-18.89
2,(주)CMG제약,58820,2013/12,38258866.0,38209699.0,4618718.0,4618718.0,-25.87,-25.93
3,(주)CMG제약,58820,2014/12,28359823.0,28300941.0,4913103.0,4913103.0,-7.15,-7.17
4,(주)CMG제약,58820,2015/12,26330765.0,26271614.0,5455617.0,5455617.0,199.16,199.84
...,...,...,...,...,...,...,...,...,...
15145,흥아해운(주),3280,2015/12,124478864.0,136280257.0,11488626.0,11488626.0,-26.92,-25.08
15146,흥아해운(주),3280,2016/12,90973953.0,102103828.0,17967554.0,17967554.0,16.32,13.29
15147,흥아해운(주),3280,2017/12,105819304.0,115675013.0,19976759.0,19976759.0,-2.49,-6.33
15148,흥아해운(주),3280,2018/12,103181415.0,108354984.0,18794127.0,18807927.0,-40.70,-13.42
15149,흥아해운(주),3280,2019/12,61182850.0,93810124.0,7544969.0,7715548.0,NaN,NaN

In [41]:
for i in range(len(q1)-1):
    if q1.loc[i,'회사명'] == q1.loc[i+1,'회사명']:
        if q1.loc[i,'재고자산(*)(IFRS연결)(천원)'] != 11111111.11:
            q1.loc[i,'3'] = (((q1.loc[i+1,'재고자산(*)(IFRS연결)(천원)'] / q1.loc[i,'재고자산(*)(IFRS연결)(천원)'])*100)-100).round(2)
        else:
            if q1.loc[i,'재고자산(*)(IFRS연결)(천원)'] == 11111111.11:
                continue
    elif q1.loc[i,'회사명'] != q1.loc[i+1,'회사명']:
        if q1.loc[i,'회사명'] == q1.loc[i-1,'회사명']:
            q1.loc[i,'3'] = (((q1.loc[i+1,'재고자산(*)(IFRS연결)(천원)'] / q1.loc[i,'재고자산(*)(IFRS연결)(천원)'])*100)-100).round(2)
        else:
            continue
q1

C:\Users\82104\AppData\Local\Temp\ipykernel_2668\2794307431.py:4: RuntimeWarning: invalid value encountered in double_scalars
  q1.loc[i,'3'] = (((q1.loc[i+1,'재고자산(*)(IFRS연결)(천원)'] / q1.loc[i,'재고자산(*)(IFRS연결)(천원)'])*100)-100).round(2)
C:\Users\82104\AppData\Local\Temp\ipykernel_2668\2794307431.py:4: RuntimeWarning: divide by zero encountered in double_scalars
  q1.loc[i,'3'] = (((q1.loc[i+1,'재고자산(*)(IFRS연결)(천원)'] / q1.loc[i,'재고자산(*)(IFRS연결)(천원)'])*100)-100).round(2)
C:\Users\82104\AppData\Local\Temp\ipykernel_2668\2794307431.py:10: RuntimeWarning: divide by zero encountered in double_scalars
  q1.loc[i,'3'] = (((q1.loc[i+1,'재고자산(*)(IFRS연결)(천원)'] / q1.loc[i,'재고자산(*)(IFRS연결)(천원)'])*100)-100).round(2)
C:\Users\82104\AppData\Local\Temp\ipykernel_2668\2794307431.py:10: RuntimeWarning: invalid value encountered in double_scalars
  q1.loc[i,'3'] = (((q1.loc[i+1,'재고자산(*)(IFRS연결)(천원)'] / q1.loc[i,'재고자산(*)(IFRS연결)(천원)'])*100)-100).round(2)

,회사명,거래소코드,회계년도,유동자산(*)(IFRS)(천원),유동자산(*)(IFRS연결)(천원),재고자산(*)(IFRS)(천원),재고자산(*)(IFRS연결)(천원),0,1,2,3
0,(주)CMG제약,58820,2011/12,15264885.0,15341167.0,2743103.0,2743103.0,208.38,207.08,7.73,7.73
1,(주)CMG제약,58820,2012/12,47073443.0,47109213.0,2955172.0,2955172.0,-18.73,-18.89,56.29,56.29
2,(주)CMG제약,58820,2013/12,38258866.0,38209699.0,4618718.0,4618718.0,-25.87,-25.93,6.37,6.37
3,(주)CMG제약,58820,2014/12,28359823.0,28300941.0,4913103.0,4913103.0,-7.15,-7.17,11.04,11.04
4,(주)CMG제약,58820,2015/12,26330765.0,26271614.0,5455617.0,5455617.0,199.16,199.84,17.20,17.20
...,...,...,...,...,...,...,...,...,...,...,...
15145,흥아해운(주),3280,2015/12,124478864.0,136280257.0,11488626.0,11488626.0,-26.92,-25.08,56.39,56.39
15146,흥아해운(주),3280,2016/12,90973953.0,102103828.0,17967554.0,17967554.0,16.32,13.29,11.18,11.18
15147,흥아해운(주),3280,2017/12,105819304.0,115675013.0,19976759.0,19976759.0,-2.49,-6.33,-5.92,-5.85
15148,흥아해운(주),3280,2018/12,103181415.0,108354984.0,18794127.0,18807927.0,-40.70,-13.42,-59.85,-58.98
15149,흥아해운(주),3280,2019/12,61182850.0,93810124.0,7544969.0,7715548.0,NaN,NaN,NaN,NaN

In [44]:
q2 = pd.read_csv('재고,유동증가율.csv',encoding='cp949')
q2 = q2.fillna(11111111.11)
q2

,Unnamed: 0,회사명,거래소코드,회계년도,유동자산(*)(IFRS)(천원),유동자산(*)(IFRS연결)(천원),재고자산(*)(IFRS)(천원),재고자산(*)(IFRS연결)(천원),0,1,2,3
0,0,(주)CMG제약,58820,Dec-11,15264885.0,15341167.0,2743103.0,2743103.0,11111111.11,11111111.11,11111111.11,11111111.11
1,1,(주)CMG제약,58820,Dec-12,47073443.0,47109213.0,2955172.0,2955172.0,208.38,207.08,7.73,7.73
2,2,(주)CMG제약,58820,Dec-13,38258866.0,38209699.0,4618718.0,4618718.0,-18.73,-18.89,56.29,56.29
3,3,(주)CMG제약,58820,Dec-14,28359823.0,28300941.0,4913103.0,4913103.0,-25.87,-25.93,6.37,6.37
4,4,(주)CMG제약,58820,Dec-15,26330765.0,26271614.0,5455617.0,5455617.0,-7.15,-7.17,11.04,11.04
...,...,...,...,...,...,...,...,...,...,...,...,...
15145,15145,흥아해운(주),3280,Dec-15,124478864.0,136280257.0,11488626.0,11488626.0,-14.23,-11.18,-12.92,-12.92
15146,15146,흥아해운(주),3280,Dec-16,90973953.0,102103828.0,17967554.0,17967554.0,-26.92,-25.08,56.39,56.39
15147,15147,흥아해운(주),3280,Dec-17,105819304.0,115675013.0,19976759.0,19976759.0,16.32,13.29,11.18,11.18
15148,15148,흥아해운(주),3280,Dec-18,103181415.0,108354984.0,18794127.0,18807927.0,-2.49,-6.33,-5.92,-5.85
15149,15149,흥아해운(주),3280,Dec-19,61182850.0,93810124.0,7544969.0,7715548.0,-40.70,-13.42,-59.85,-58.98

In [47]:
q3 = pd.concat([df[['회사명','유동자산증가율','재고자산증가율']],q2[['0','1','2','3']]],axis=1)
q3

,회사명,유동자산증가율,재고자산증가율,0,1,2,3
0,(주)CMG제약,17.64,-1.43,11111111.11,11111111.11,11111111.11,11111111.11
1,(주)CMG제약,207.08,7.73,208.38,207.08,7.73,7.73
2,(주)CMG제약,-18.89,56.29,-18.73,-18.89,56.29,56.29
3,(주)CMG제약,-25.93,6.37,-25.87,-25.93,6.37,6.37
4,(주)CMG제약,-7.17,11.04,-7.15,-7.17,11.04,11.04
...,...,...,...,...,...,...,...
15145,흥아해운(주),-11.18,-12.92,-14.23,-11.18,-12.92,-12.92
15146,흥아해운(주),-25.08,56.39,-26.92,-25.08,56.39,56.39
15147,흥아해운(주),13.29,11.18,16.32,13.29,11.18,11.18
15148,흥아해운(주),-6.33,-5.85,-2.49,-6.33,-5.92,-5.85
15149,흥아해운(주),-13.42,-58.98,-40.70,-13.42,-59.85,-58.98

In [48]:
for i in range(len(q3)):
    if q3.loc[i,'유동자산증가율'] == 0:
        if q3.loc[i,'0'] != 11111111.11:
            if q3.loc[i,'1'] != 11111111.11:
                q3.loc[i,'유동자산증가율'] = q3.loc[i,'1']
            else:
                q3.loc[i,'유동자산증가율'] = q3.loc[i,'0']
        else:
            if q3.loc[i,'1'] != 11111111.11:
                q3.loc[i,'유동자산증가율'] = q3.loc[i,'1']
            else:
                q3.loc[i,'유동자산증가율'] = 1254789.63
        if q3.loc[i,'1'] == 0:
            q3.loc[i,'유동자산증가율'] = q3.loc[i,'0']
        if q3.loc[i,'1'] == 11111111.11:
            q3.loc[i,'유동자산증가율'] = 11111111.11
    if q3.loc[i,'유동자산증가율'] == 11111111.11:
        if q3.loc[i,'1'] != 11111111.11:
            if q3.loc[i,'0'] != 11111111.11:
                q3.loc[i,'유동자산증가율'] = q3.loc[i,'1']
            else:
                q3.loc[i,'유동자산증가율'] = q3.loc[i,'1']
        if q3.loc[i,'1'] == 11111111.11:
            if q3.loc[i,'0'] != 11111111.11:
                q3.loc[i,'유동자산증가율'] = q3.loc[i,'0']
            else:
                q3.loc[i,'유동자산증가율'] = 1254789.63
        
q3

,회사명,유동자산증가율,재고자산증가율,0,1,2,3
0,(주)CMG제약,17.64,-1.43,11111111.11,11111111.11,11111111.11,11111111.11
1,(주)CMG제약,207.08,7.73,208.38,207.08,7.73,7.73
2,(주)CMG제약,-18.89,56.29,-18.73,-18.89,56.29,56.29
3,(주)CMG제약,-25.93,6.37,-25.87,-25.93,6.37,6.37
4,(주)CMG제약,-7.17,11.04,-7.15,-7.17,11.04,11.04
...,...,...,...,...,...,...,...
15145,흥아해운(주),-11.18,-12.92,-14.23,-11.18,-12.92,-12.92
15146,흥아해운(주),-25.08,56.39,-26.92,-25.08,56.39,56.39
15147,흥아해운(주),13.29,11.18,16.32,13.29,11.18,11.18
15148,흥아해운(주),-6.33,-5.85,-2.49,-6.33,-5.92,-5.85
15149,흥아해운(주),-13.42,-58.98,-40.70,-13.42,-59.85,-58.98

In [49]:
for i in range(len(q3)):
    if q3.loc[i,'재고자산증가율'] == 0:
        if q3.loc[i,'2'] != 11111111.11:
            if q3.loc[i,'3'] != 11111111.11:
                q3.loc[i,'재고자산증가율'] = q3.loc[i,'3']
            else:
                q3.loc[i,'재고자산증가율'] = q3.loc[i,'2']
        else:
            if q3.loc[i,'3'] != 11111111.11:
                q3.loc[i,'재고자산증가율'] = q3.loc[i,'3']
            else:
                q3.loc[i,'재고자산증가율'] = 1254789.63
        if q3.loc[i,'3'] == 0:
            q3.loc[i,'재고자산증가율'] = q3.loc[i,'2']
        if q3.loc[i,'3'] == 11111111.11:
            q3.loc[i,'재고자산증가율'] = 11111111.11
    if q3.loc[i,'재고자산증가율'] == 11111111.11:
        if q3.loc[i,'3'] != 11111111.11:
            if q3.loc[i,'2'] != 11111111.11:
                q3.loc[i,'재고자산증가율'] = q3.loc[i,'3']
            else:
                q3.loc[i,'재고자산증가율'] = q3.loc[i,'3']
        if q3.loc[i,'3'] == 11111111.11:
            if q3.loc[i,'2'] != 11111111.11:
                q3.loc[i,'재고자산증가율'] = q3.loc[i,'2']
            else:
                q3.loc[i,'재고자산증가율'] = 1254789.63
        
q3

,회사명,유동자산증가율,재고자산증가율,0,1,2,3
0,(주)CMG제약,17.64,-1.43,11111111.11,11111111.11,11111111.11,11111111.11
1,(주)CMG제약,207.08,7.73,208.38,207.08,7.73,7.73
2,(주)CMG제약,-18.89,56.29,-18.73,-18.89,56.29,56.29
3,(주)CMG제약,-25.93,6.37,-25.87,-25.93,6.37,6.37
4,(주)CMG제약,-7.17,11.04,-7.15,-7.17,11.04,11.04
...,...,...,...,...,...,...,...
15145,흥아해운(주),-11.18,-12.92,-14.23,-11.18,-12.92,-12.92
15146,흥아해운(주),-25.08,56.39,-26.92,-25.08,56.39,56.39
15147,흥아해운(주),13.29,11.18,16.32,13.29,11.18,11.18
15148,흥아해운(주),-6.33,-5.85,-2.49,-6.33,-5.92,-5.85
15149,흥아해운(주),-13.42,-58.98,-40.70,-13.42,-59.85,-58.98

In [72]:
e1 = pd.read_csv('자기자본.csv',encoding='cp949')
e1 = e1.fillna(11111111.11)
e1

            회사명  거래소코드     회계년도  합계(IFRS)(천원)  합계(IFRS연결)(천원)
0      (주)CMG제약  58820  2011/12    18290915.0      18034249.0
1      (주)CMG제약  58820  2012/12    31602540.0      31590684.0
2      (주)CMG제약  58820  2013/12    49048213.0      48997281.0
3      (주)CMG제약  58820  2014/12    49067039.0      49002644.0
4      (주)CMG제약  58820  2015/12    46872705.0      46806888.0
...         ...    ...      ...           ...             ...
15145   흥아해운(주)   3280  2015/12   161824549.0     173076634.0
15146   흥아해운(주)   3280  2016/12   183829287.0     192487245.0
15147   흥아해운(주)   3280  2017/12   107614965.0     116884496.0
15148   흥아해운(주)   3280  2018/12    56731554.0      73148175.0
15149   흥아해운(주)   3280  2019/12    17632229.0      30919383.0

[15150 rows x 5 columns]

In [73]:
for i in range(len(e1)-1):
    if e1.loc[i,'회사명'] == e1.loc[i+1,'회사명']:
        if e1.loc[i,'합계(IFRS)(천원)'] != 11111111.11:
            e1.loc[i,'0'] = (((e1.loc[i+1,'합계(IFRS)(천원)'] - e1.loc[i,'합계(IFRS)(천원)'])/e1.loc[i,'합계(IFRS)(천원)'])*100).round(2)
        else:
            if e1.loc[i,'합계(IFRS)(천원)'] == 11111111.11:
                continue
    elif e1.loc[i,'회사명'] != e1.loc[i+1,'회사명']:
        if e1.loc[i,'회사명'] == e1.loc[i-1,'회사명']:
            e1.loc[i,'0'] = (((e1.loc[i+1,'합계(IFRS)(천원)'] - e1.loc[i,'합계(IFRS)(천원)'])/e1.loc[i,'합계(IFRS)(천원)'])*100).round(2)
        else:
            continue
e1

            회사명  거래소코드     회계년도  합계(IFRS)(천원)  합계(IFRS연결)(천원)       0
0      (주)CMG제약  58820  2011/12    18290915.0      18034249.0   72.78
1      (주)CMG제약  58820  2012/12    31602540.0      31590684.0   55.20
2      (주)CMG제약  58820  2013/12    49048213.0      48997281.0    0.04
3      (주)CMG제약  58820  2014/12    49067039.0      49002644.0   -4.47
4      (주)CMG제약  58820  2015/12    46872705.0      46806888.0  115.71
...         ...    ...      ...           ...             ...     ...
15145   흥아해운(주)   3280  2015/12   161824549.0     173076634.0   13.60
15146   흥아해운(주)   3280  2016/12   183829287.0     192487245.0  -41.46
15147   흥아해운(주)   3280  2017/12   107614965.0     116884496.0  -47.28
15148   흥아해운(주)   3280  2018/12    56731554.0      73148175.0  -68.92
15149   흥아해운(주)   3280  2019/12    17632229.0      30919383.0     NaN

[15150 rows x 6 columns]

In [76]:
for i in range(len(e1)-1):
    if e1.loc[i,'회사명'] == e1.loc[i+1,'회사명']:
        if e1.loc[i,'합계(IFRS연결)(천원)'] != 11111111.11:
            e1.loc[i,'1'] = (((e1.loc[i+1,'합계(IFRS연결)(천원)'] - e1.loc[i,'합계(IFRS연결)(천원)'])/e1.loc[i,'합계(IFRS연결)(천원)'])*100).round(2)
        else:
            if e1.loc[i,'합계(IFRS연결)(천원)'] == 11111111.11:
                continue
    elif e1.loc[i,'회사명'] != e1.loc[i+1,'회사명']:
        if e1.loc[i,'회사명'] == e1.loc[i-1,'회사명']:
            e1.loc[i,'1'] = (((e1.loc[i+1,'합계(IFRS연결)(천원)'] - e1.loc[i,'합계(IFRS연결)(천원)'])/e1.loc[i,'합계(IFRS연결)(천원)'])*100).round(2)
        else:
            continue
e1

            회사명  거래소코드     회계년도  합계(IFRS)(천원)  합계(IFRS연결)(천원)       0       1
0      (주)CMG제약  58820  2011/12    18290915.0      18034249.0   72.78   75.17
1      (주)CMG제약  58820  2012/12    31602540.0      31590684.0   55.20   55.10
2      (주)CMG제약  58820  2013/12    49048213.0      48997281.0    0.04    0.01
3      (주)CMG제약  58820  2014/12    49067039.0      49002644.0   -4.47   -4.48
4      (주)CMG제약  58820  2015/12    46872705.0      46806888.0  115.71  116.01
...         ...    ...      ...           ...             ...     ...     ...
15145   흥아해운(주)   3280  2015/12   161824549.0     173076634.0   13.60   11.22
15146   흥아해운(주)   3280  2016/12   183829287.0     192487245.0  -41.46  -39.28
15147   흥아해운(주)   3280  2017/12   107614965.0     116884496.0  -47.28  -37.42
15148   흥아해운(주)   3280  2018/12    56731554.0      73148175.0  -68.92  -57.73
15149   흥아해운(주)   3280  2019/12    17632229.0      30919383.0     NaN     NaN

[15150 rows x 7 columns]

In [77]:
# e1.to_csv('자기자본증가율.csv',encoding='cp949')

In [78]:
e2 = pd.read_csv('자기자본증가율.csv',encoding='cp949')
e2 = e2.fillna(11111111.11)
e2

,Unnamed: 0,회사명,거래소코드,회계년도,합계(IFRS)(천원),합계(IFRS연결)(천원),0,1
0,0,(주)CMG제약,58820,Dec-11,18290915.0,18034249.0,11111111.11,11111111.11
1,1,(주)CMG제약,58820,Dec-12,31602540.0,31590684.0,72.78,75.17
2,2,(주)CMG제약,58820,Dec-13,49048213.0,48997281.0,55.20,55.10
3,3,(주)CMG제약,58820,Dec-14,49067039.0,49002644.0,0.04,0.01
4,4,(주)CMG제약,58820,Dec-15,46872705.0,46806888.0,-4.47,-4.48
...,...,...,...,...,...,...,...,...
15145,15145,흥아해운(주),3280,Dec-15,161824549.0,173076634.0,5.12,3.39
15146,15146,흥아해운(주),3280,Dec-16,183829287.0,192487245.0,13.60,11.22
15147,15147,흥아해운(주),3280,Dec-17,107614965.0,116884496.0,-41.46,-39.28
15148,15148,흥아해운(주),3280,Dec-18,56731554.0,73148175.0,-47.28,-37.42
15149,15149,흥아해운(주),3280,Dec-19,17632229.0,30919383.0,-68.92,-57.73

In [95]:
e3 = pd.concat([df['자기자본증가율'],e2[['0','1']]],axis=1)
e3

       자기자본증가율            0            1
0        -2.02  11111111.11  11111111.11
1        75.17        72.78        75.17
2        55.10        55.20        55.10
3         0.01         0.04         0.01
4        -4.48        -4.47        -4.48
...        ...          ...          ...
15145     3.39         5.12         3.39
15146    11.22        13.60        11.22
15147   -39.28       -41.46       -39.28
15148   -37.42       -47.28       -37.42
15149   -57.73       -68.92       -57.73

[15150 rows x 3 columns]

In [97]:
for i in range(len(e3)):
    if e3.loc[i,'자기자본증가율'] == 0:
        if e3.loc[i,'0'] != 11111111.11:
            if e3.loc[i,'1'] != 11111111.11:
                e3.loc[i,'자기자본증가율'] = e3.loc[i,'1']
            else:
                e3.loc[i,'자기자본증가율'] = e3.loc[i,'0']
        else:
            if e3.loc[i,'1'] != 11111111.11:
                e3.loc[i,'자기자본증가율'] = e3.loc[i,'1']
            else:
                e3.loc[i,'자기자본증가율'] = 1254789.63
        if e3.loc[i,'1'] == 0:
            e3.loc[i,'자기자본증가율'] = e3.loc[i,'0']
        if e3.loc[i,'1'] == 11111111.11:
            e3.loc[i,'자기자본증가율'] = 11111111.11
    if e3.loc[i,'자기자본증가율'] == 11111111.11:
        if e3.loc[i,'1'] != 11111111.11:
            if e3.loc[i,'0'] != 11111111.11:
                e3.loc[i,'자기자본증가율'] = e3.loc[i,'1']
            else:
                e3.loc[i,'자기자본증가율'] = e3.loc[i,'1']
        if e3.loc[i,'1'] == 11111111.11:
            if e3.loc[i,'0'] != 11111111.11:
                e3.loc[i,'자기자본증가율'] = e3.loc[i,'0']
            else:
                e3.loc[i,'자기자본증가율'] = 1254789.63
        
e3

       자기자본증가율            0            1
0        -2.02  11111111.11  11111111.11
1        75.17        72.78        75.17
2        55.10        55.20        55.10
3         0.01         0.04         0.01
4        -4.48        -4.47        -4.48
...        ...          ...          ...
15145     3.39         5.12         3.39
15146    11.22        13.60        11.22
15147   -39.28       -41.46       -39.28
15148   -37.42       -47.28       -37.42
15149   -57.73       -68.92       -57.73

[15150 rows x 3 columns]

In [98]:
e3.to_csv('자기자본증가율최종.csv',encoding='cp949')

In [70]:
w1[w1['기초자본금(IFRS연결)(천원)']==0]

,회사명,거래소코드,회계년도,기말자본금(*)(IFRS)(천원),기초자본금(IFRS)(천원),기말자본금(*)(IFRS연결)(천원),기초자본금(IFRS연결)(천원),매출액(수익)(*)(IFRS)(천원),매출액(수익)(*)(IFRS연결)(천원),0,1,2,3
158,(주)경동도시가스,267290,2017/12,11792658.00,0.00,11792658.0,0.0,8.708289e+08,8.715483e+08,inf,inf,84.39,84.33
226,(주)골프존,215000,2015/12,3137708.00,0.00,3137708.0,0.0,1.840853e+08,2.015604e+08,inf,inf,6.94,7.64
1776,(주)만도,204320,2014/12,46957120.00,0.00,46957120.0,0.0,1.047182e+09,1.721436e+09,inf,inf,195.47,207.84
3414,(주)심텍,222800,2015/12,10972708.00,0.00,10972708.0,0.0,3.851302e+08,3.954707e+08,inf,inf,98.22,100.27
5844,(주)이녹스첨단소재,272290,2017/12,4330421.00,0.00,4330421.0,0.0,1.923463e+08,1.931041e+08,inf,inf,52.08,51.79
9150,(주)휴온스,243070,2016/12,2947732.00,0.00,2947732.0,0.0,1.675722e+08,1.689661e+08,inf,inf,65.91,68.58
9203,HD현대(주),267250,2017/12,81433085.00,60202105.00,81433085.0,0.0,4.652417e+08,1.429951e+10,35.27,inf,24.52,90.61
10405,동화기업(주),25900,2017/12,7678378.00,7678378.00,7678378.0,0.0,4.370017e+08,7.787861e+08,0.00,inf,0.35,-2.42
10592,롯데제과(주),280360,2017/12,2104551.00,0.00,2104551.0,0.0,4.034863e+08,4.047875e+08,inf,inf,293.10,318.62
11356,샘표식품(주),248170,2016/12,2284143.00,0.00,2284143.0,0.0,1.311963e+08,1.350655e+08,inf,inf,104.19,103.36
11570,솔루스첨단소재(주),336370,2019/12,3960221.00,0.00,3960221.0,0.0,4.484948e+07,6.999477e+07,NaN,NaN,NaN,NaN
11910,아세아시멘트(주),183190,2013/12,16479045.00,0.00,16479045.0,0.0,1.082903e+08,1.169455e+08,inf,inf,269.03,262.87
12394,에이피시스템(주),265520,2017/12,7640711.00,0.00,7640711.0,0.0,9.624227e+08,9.624227e+08,inf,inf,-25.81,-25.79
12460,엔에이치엔(주),181710,2013/12,7582513.00,0.00,7582513.0,0.0,1.813245e+08,2.653485e+08,inf,inf,33.91,109.86
12731,우리산업(주),215360,2015/12,4566082.00,0.00,4566082.0,0.0,1.967173e+08,1.967173e+08,inf,inf,31.55,31.55
13626,케이만금세기차륜집단유한공사,900280,2015/12,11111111.11,11111111.11,4820281.0,0.0,1.111111e+07,7.780557e+07,1254789.63,inf,NaN,16.96
14489,한국콜마(주),161890,2013/03,9741886.00,0.00,9741886.0,0.0,1.740381e+08,1.777792e+08,inf,inf,152.29,159.45
14637,한솔제지(주),213500,2015/12,82682545.00,0.00,82682545.0,0.0,1.349589e+09,1.511653e+09,inf,inf,-0.08,1.25

In [56]:
# w1.to_csv('자기자본,매출증가율.csv',encoding='cp949')

In [61]:
w2 = pd.read_csv('자기자본,매출증가율.csv',encoding='cp949')
w2 = w2.fillna(11111111.11)
w2

,Unnamed: 0,회사명,거래소코드,회계년도,기말자본금(*)(IFRS)(천원),기초자본금(IFRS)(천원),기말자본금(*)(IFRS연결)(천원),기초자본금(IFRS연결)(천원),매출액(수익)(*)(IFRS)(천원),매출액(수익)(*)(IFRS연결)(천원),0,1,2,3
0,0,(주)CMG제약,58820,Dec-11,21846600.0,20588188.0,21846600.0,20588188.0,17751704.0,17751704.0,11111111.11,11111111.11,11111111.11,11111111.11
1,1,(주)CMG제약,58820,Dec-12,33012770.0,21846600.0,33012770.0,21846600.0,16255389.0,16255389.0,60.35,60.35,-8.43,-8.43
2,2,(주)CMG제약,58820,Dec-13,43313433.0,33012770.0,43313433.0,33012770.0,20322140.0,20402140.0,98.26,98.26,25.02,25.51
3,3,(주)CMG제약,58820,Dec-14,43313433.0,43313433.0,43313433.0,43313433.0,22752584.0,22752584.0,31.20,31.20,11.96,11.52
4,4,(주)CMG제약,58820,Dec-15,44148622.0,43313433.0,44148622.0,43313433.0,27041894.0,27041894.0,1.93,1.93,18.85,18.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15145,15145,흥아해운(주),3280,Dec-15,42356715.0,42356715.0,42356715.0,42356715.0,801560945.0,845115359.0,0.00,0.00,1.56,2.42
15146,15146,흥아해운(주),3280,Dec-16,63856715.0,42356715.0,63856715.0,42356715.0,779990350.0,831746081.0,50.76,50.76,-2.69,-1.58
15147,15147,흥아해운(주),3280,Dec-17,63856715.0,63856715.0,63856715.0,63856715.0,780863972.0,836427496.0,50.76,50.76,0.11,0.56
15148,15148,흥아해운(주),3280,Dec-18,87821715.0,63856715.0,87821715.0,63856715.0,705007198.0,753865569.0,37.53,37.53,-9.71,-9.87
15149,15149,흥아해운(주),3280,Dec-19,56056196.0,87821715.0,56056196.0,87821715.0,97376909.0,102166838.0,-12.22,-12.22,-86.19,-86.45

In [63]:
w3 = pd.concat([df['매출액증가율'],w2[['2','3']]], axis=1)
w3

       매출액증가율            2            3
0       56.40  11111111.11  11111111.11
1       -8.43        -8.43        -8.43
2       25.51        25.02        25.51
3       11.52        11.96        11.52
4       18.85        18.85        18.85
...       ...          ...          ...
15145    2.42         1.56         2.42
15146   -1.58        -2.69        -1.58
15147    0.56         0.11         0.56
15148   -9.87        -9.71        -9.87
15149  -86.45       -86.19       -86.45

[15150 rows x 3 columns]

In [64]:
for i in range(len(w3)):
    if w3.loc[i,'매출액증가율'] == 0:
        if w3.loc[i,'2'] != 11111111.11:
            if w3.loc[i,'3'] != 11111111.11:
                w3.loc[i,'매출액증가율'] = w3.loc[i,'3']
            else:
                w3.loc[i,'매출액증가율'] = w3.loc[i,'2']
        else:
            if w3.loc[i,'3'] != 11111111.11:
                w3.loc[i,'매출액증가율'] = w3.loc[i,'3']
            else:
                w3.loc[i,'매출액증가율'] = 1254789.63
        if w3.loc[i,'3'] == 0:
            w3.loc[i,'매출액증가율'] = w3.loc[i,'2']
        if w3.loc[i,'3'] == 11111111.11:
            w3.loc[i,'매출액증가율'] = 11111111.11
    if w3.loc[i,'매출액증가율'] == 11111111.11:
        if w3.loc[i,'3'] != 11111111.11:
            if w3.loc[i,'2'] != 11111111.11:
                w3.loc[i,'매출액증가율'] = w3.loc[i,'3']
            else:
                w3.loc[i,'매출액증가율'] = w3.loc[i,'3']
        if w3.loc[i,'3'] == 11111111.11:
            if w3.loc[i,'2'] != 11111111.11:
                w3.loc[i,'매출액증가율'] = w3.loc[i,'2']
            else:
                w3.loc[i,'매출액증가율'] = 1254789.63
        
w3

       매출액증가율            2            3
0       56.40  11111111.11  11111111.11
1       -8.43        -8.43        -8.43
2       25.51        25.02        25.51
3       11.52        11.96        11.52
4       18.85        18.85        18.85
...       ...          ...          ...
15145    2.42         1.56         2.42
15146   -1.58        -2.69        -1.58
15147    0.56         0.11         0.56
15148   -9.87        -9.71        -9.87
15149  -86.45       -86.19       -86.45

[15150 rows x 3 columns]

In [65]:
# w3.to_csv('매출증가율최종.csv',encoding='cp949')

In [101]:
w3[w3['매출액증가율']==1254789.63]

           매출액증가율            2            3
194    1254789.63  11111111.11  11111111.11
195    1254789.63  11111111.11  11111111.11
196    1254789.63  11111111.11  11111111.11
331    1254789.63  11111111.11  11111111.11
411    1254789.63  11111111.11  11111111.11
...           ...          ...          ...
14094  1254789.63  11111111.11  11111111.11
14095  1254789.63  11111111.11  11111111.11
15122  1254789.63  11111111.11  11111111.11
15123  1254789.63  11111111.11  11111111.11
15124  1254789.63  11111111.11  11111111.11

[192 rows x 3 columns]

In [118]:
test = pd.read_csv('자기자본.csv',encoding='cp949')
test

            회사명  거래소코드     회계년도  합계(IFRS)(천원)  합계(IFRS연결)(천원)
0      (주)CMG제약  58820  2011/12    18290915.0      18034249.0
1      (주)CMG제약  58820  2012/12    31602540.0      31590684.0
2      (주)CMG제약  58820  2013/12    49048213.0      48997281.0
3      (주)CMG제약  58820  2014/12    49067039.0      49002644.0
4      (주)CMG제약  58820  2015/12    46872705.0      46806888.0
...         ...    ...      ...           ...             ...
15145   흥아해운(주)   3280  2015/12   161824549.0     173076634.0
15146   흥아해운(주)   3280  2016/12   183829287.0     192487245.0
15147   흥아해운(주)   3280  2017/12   107614965.0     116884496.0
15148   흥아해운(주)   3280  2018/12    56731554.0      73148175.0
15149   흥아해운(주)   3280  2019/12    17632229.0      30919383.0

[15150 rows x 5 columns]

In [119]:
test['합계개별'] = test['합계(IFRS)(천원)'].shift().where(test.회사명.eq(test.회사명.shift()))
test

            회사명  거래소코드     회계년도  합계(IFRS)(천원)  합계(IFRS연결)(천원)         합계개별
0      (주)CMG제약  58820  2011/12    18290915.0      18034249.0          NaN
1      (주)CMG제약  58820  2012/12    31602540.0      31590684.0   18290915.0
2      (주)CMG제약  58820  2013/12    49048213.0      48997281.0   31602540.0
3      (주)CMG제약  58820  2014/12    49067039.0      49002644.0   49048213.0
4      (주)CMG제약  58820  2015/12    46872705.0      46806888.0   49067039.0
...         ...    ...      ...           ...             ...          ...
15145   흥아해운(주)   3280  2015/12   161824549.0     173076634.0  153935831.0
15146   흥아해운(주)   3280  2016/12   183829287.0     192487245.0  161824549.0
15147   흥아해운(주)   3280  2017/12   107614965.0     116884496.0  183829287.0
15148   흥아해운(주)   3280  2018/12    56731554.0      73148175.0  107614965.0
15149   흥아해운(주)   3280  2019/12    17632229.0      30919383.0   56731554.0

[15150 rows x 6 columns]

In [120]:
test['합계개별율'] = (test['합계(IFRS)(천원)'] - test['합계개별'])/test['합계개별']
test

,회사명,거래소코드,회계년도,합계(IFRS)(천원),합계(IFRS연결)(천원),합계개별,합계개별율
0,(주)CMG제약,58820,2011/12,18290915.0,18034249.0,NaN,NaN
1,(주)CMG제약,58820,2012/12,31602540.0,31590684.0,18290915.0,0.727773
2,(주)CMG제약,58820,2013/12,49048213.0,48997281.0,31602540.0,0.552034
3,(주)CMG제약,58820,2014/12,49067039.0,49002644.0,49048213.0,0.000384
4,(주)CMG제약,58820,2015/12,46872705.0,46806888.0,49067039.0,-0.044721
...,...,...,...,...,...,...,...
15145,흥아해운(주),3280,2015/12,161824549.0,173076634.0,153935831.0,0.051247
15146,흥아해운(주),3280,2016/12,183829287.0,192487245.0,161824549.0,0.135979
15147,흥아해운(주),3280,2017/12,107614965.0,116884496.0,183829287.0,-0.414593
15148,흥아해운(주),3280,2018/12,56731554.0,73148175.0,107614965.0,-0.472828
15149,흥아해운(주),3280,2019/12,17632229.0,30919383.0,56731554.0,-0.689199

In [121]:
test[8:22]

,회사명,거래소코드,회계년도,합계(IFRS)(천원),합계(IFRS연결)(천원),합계개별,합계개별율
8,(주)CMG제약,58820,2019/12,180158283.0,180158283.0,103981846.0,0.732594
9,(주)DB하이텍,990,2011/12,291709498.0,308061688.0,NaN,NaN
10,(주)DB하이텍,990,2012/12,274553219.0,290893335.0,291709498.0,-0.058813
11,(주)DB하이텍,990,2013/12,197287466.0,204756748.0,274553219.0,-0.281424
12,(주)DB하이텍,990,2014/12,136104062.0,120702734.0,197287466.0,-0.310123
13,(주)DB하이텍,990,2015/12,277662952.0,254057491.0,136104062.0,1.040078
14,(주)DB하이텍,990,2016/12,364450453.0,341917315.0,277662952.0,0.312564
15,(주)DB하이텍,990,2017/12,441546809.0,455797947.0,364450453.0,0.211541
16,(주)DB하이텍,990,2018/12,542557222.0,558391531.0,441546809.0,0.228765
17,(주)DB하이텍,990,2019/12,645305205.0,644650730.0,542557222.0,0.189377
18,(주)ES큐브,50120,2011/12,39144414.0,39245830.0,NaN,NaN
19,(주)ES큐브,50120,2012/12,39881477.0,39859681.0,39144414.0,0.018829
20,(주)ES큐브,50120,2013/12,43712820.0,42372440.0,39881477.0,0.096068
21,(주)ES큐브,50120,2014/12,41226335.0,49628091.0,43712820.0,-0.056882

In [229]:
qq1 = pd.read_csv('영업이익진.csv',encoding='cp949')
qq1 = qq1.fillna(11111111.11)
qq1['영업이익개별스'] = qq1['영업이익(개별)'].shift().where(qq1.회사명.eq(qq1.회사명.shift()))
qq1['영업이익연결스'] = qq1['영업이익(연결)'].shift().where(qq1.회사명.eq(qq1.회사명.shift()))
qq1['회계년도'] = pd.to_datetime(qq1['회계년도'], format='%b-%d').dt.strftime('20%d')
qq1

            회사명  거래소코드  회계년도  영업이익(개별)  영업이익(연결)     영업이익개별스     영업이익연결스
0      (주)CMG제약  58820  2010  -7537070  -7537070         NaN         NaN
1      (주)CMG제약  58820  2011    714950    640282  -7537070.0  -7537070.0
2      (주)CMG제약  58820  2012  -4045140  -4205504    714950.0    640282.0
3      (주)CMG제약  58820  2013    822547    791250  -4045140.0  -4205504.0
4      (주)CMG제약  58820  2014    446017    442322    822547.0    791250.0
...         ...    ...   ...       ...       ...         ...         ...
16498   흥아해운(주)   3280  2015  16258441  21244278  15856524.0  18568741.0
16499   흥아해운(주)   3280  2016   1154122   5895873  16258441.0  21244278.0
16500   흥아해운(주)   3280  2017 -18649057 -13098624   1154122.0   5895873.0
16501   흥아해운(주)   3280  2018 -40598235 -37595967 -18649057.0 -13098624.0
16502   흥아해운(주)   3280  2019 -14756167 -12364292 -40598235.0 -37595967.0

[16503 rows x 7 columns]

In [230]:
qq1[qq1['영업이익(개별)']==0]

            회사명   거래소코드  회계년도  영업이익(개별)  영업이익(연결)  영업이익개별스     영업이익연결스
213    (주)고려시멘트  198440  2014         0         0      NaN         NaN
214    (주)고려시멘트  198440  2015         0         0      0.0         0.0
215    (주)고려시멘트  198440  2016         0         0      0.0         0.0
363     (주)국전약품  307750  2018         0         0      NaN         NaN
364     (주)국전약품  307750  2019         0         0      0.0         0.0
...         ...     ...   ...       ...       ...      ...         ...
16204  헝셩그룹유한회사  900270  2019         0  43907646      0.0  34536637.0
16255  현대무벡스(주)  319400  2019         0         0      NaN         NaN
16472   휴마시스(주)  205470  2014         0         0      NaN         NaN
16473   휴마시스(주)  205470  2015         0         0      0.0         0.0
16474   휴마시스(주)  205470  2016         0         0      0.0         0.0

[290 rows x 7 columns]

In [231]:
for i in range(0, len(qq1)-1):
    if qq1.loc[i,'회사명'] == qq1.loc[i+1,'회사명']:
        # 음수, 음수
        if qq1.iloc[i]["영업이익(개별)"] < 0 and qq1.iloc[i]["영업이익개별스"] < 0 :
            qq1.loc[i, "영업이익증가률개별"] = 11111111.11
        # 양수, 음수
        elif qq1.iloc[i]["영업이익(개별)"] > 0 and qq1.iloc[i]["영업이익개별스"] < 0:
            qq1.loc[i, "영업이익증가률개별"] = 11111111.11
        # 음수, 양수
        elif qq1.iloc[i]["영업이익(개별)"] < 0 and qq1.iloc[i]["영업이익개별스"] > 0:
            qq1.loc[i, "영업이익증가률개별"] = (((qq1.iloc[i]["영업이익(개별)"]-qq1.iloc[i]["영업이익개별스"]) / qq1.iloc[i]["영업이익개별스"])*100).round(2)
        # 양수, 양수
        elif qq1.iloc[i]["영업이익(개별)"] > 0 and qq1.iloc[i]["영업이익개별스"] > 0:
            qq1.loc[i, "영업이익증가률개별"] = (((qq1.iloc[i]["영업이익(개별)"]-qq1.iloc[i]["영업이익개별스"]) / qq1.iloc[i]["영업이익개별스"])*100).round(2)
        # 두개 중 하나라도 0이 있으면
        elif qq1.iloc[i]["영업이익(개별)"] == 0:
            qq1.loc[i, "영업이익증가률개별"] = 0
        elif qq1.iloc[i]["영업이익개별스"] == 0:
            qq1.loc[i, "영업이익증가률개별"] = 11111111.11
        else:
            qq1.loc[i, "영업이익증가률개별"] = 1254789.63
    elif qq1.loc[i,'회사명'] != qq1.loc[i-1,'회사명']:
        # 음수, 음수
        if qq1.iloc[i]["영업이익(개별)"] < 0 and qq1.iloc[i]["영업이익개별스"] < 0 :
            qq1.loc[i, "영업이익증가률개별"] = 11111111.11
        # 양수, 음수
        elif qq1.iloc[i]["영업이익(개별)"] > 0 and qq1.iloc[i]["영업이익개별스"] < 0:
            qq1.loc[i, "영업이익증가률개별"] = 11111111.11
        # 음수, 양수
        elif qq1.iloc[i]["영업이익(개별)"] < 0 and qq1.iloc[i]["영업이익개별스"] > 0:
            qq1.loc[i, "영업이익증가률개별"] = (((qq1.iloc[i]["영업이익(개별)"]-qq1.iloc[i]["영업이익개별스"]) / qq1.iloc[i]["영업이익개별스"])*100).round(2)
        # 양수, 양수
        elif qq1.iloc[i]["영업이익(개별)"] > 0 and qq1.iloc[i]["영업이익개별스"] > 0:
            qq1.loc[i, "영업이익증가률개별"] = (((qq1.iloc[i]["영업이익(개별)"]-qq1.iloc[i]["영업이익개별스"]) / qq1.iloc[i]["영업이익개별스"])*100).round(2)
        # 두개 중 하나라도 0이 있으면
        elif qq1.iloc[i]["영업이익(개별)"] == 0:
            qq1.loc[i, "영업이익증가률개별"] = 0
        elif qq1.iloc[i]["영업이익개별스"] == 0:
            qq1.loc[i, "영업이익증가률개별"] = 11111111.11
        else:
            qq1.loc[i, "영업이익증가률개별"] = 1254789.63
        
qq1.head(25)

,회사명,거래소코드,회계년도,영업이익(개별),영업이익(연결),영업이익개별스,영업이익연결스,영업이익증가률개별
0,(주)CMG제약,58820,2010,-7537070,-7537070,NaN,NaN,1254789.63
1,(주)CMG제약,58820,2011,714950,640282,-7537070.0,-7537070.0,11111111.11
2,(주)CMG제약,58820,2012,-4045140,-4205504,714950.0,640282.0,-665.79
3,(주)CMG제약,58820,2013,822547,791250,-4045140.0,-4205504.0,11111111.11
4,(주)CMG제약,58820,2014,446017,442322,822547.0,791250.0,-45.78
5,(주)CMG제약,58820,2015,-2570878,-2572169,446017.0,442322.0,-676.41
6,(주)CMG제약,58820,2016,1730753,1730753,-2570878.0,-2572169.0,11111111.11
7,(주)CMG제약,58820,2017,1558607,1558607,1730753.0,1730753.0,-9.95
8,(주)CMG제약,58820,2018,2567820,2567820,1558607.0,1558607.0,64.75
9,(주)CMG제약,58820,2019,2603774,2603774,2567820.0,2567820.0,NaN
10,(주)DB하이텍,990,2010,-362804082,-378471909,NaN,NaN,1254789.63
11,(주)DB하이텍,990,2011,-39983672,-43150444,-362804082.0,-378471909.0,11111111.11
12,(주)DB하이텍,990,2012,-14429658,-15621631,-39983672.0,-43150444.0,11111111.11
13,(주)DB하이텍,990,2013,-9392980,-9610612,-14429658.0,-15621631.0,11111111.11
14,(주)DB하이텍,990,2014,45310506,45560248,-9392980.0,-9610612.0,11111111.11
15,(주)DB하이텍,990,2015,124372823,124968815,45310506.0,45560248.0,174.49
16,(주)DB하이텍,990,2016,171787648,172427930,124372823.0,124968815.0,38.12
17,(주)DB하이텍,990,2017,142353689,143195167,171787648.0,172427930.0,-17.13
18,(주)DB하이텍,990,2018,112884303,112993143,142353689.0,143195167.0,-20.70
19,(주)DB하이텍,990,2019,181155872,181292188,112884303.0,112993143.0,NaN
20,(주)ES큐브,50120,2010,577543,-533613,NaN,NaN,1254789.63
21,(주)ES큐브,50120,2011,-2080143,-3650245,577543.0,-533613.0,-460.17
22,(주)ES큐브,50120,2012,645839,89337,-2080143.0,-3650245.0,11111111.11
23,(주)ES큐브,50120,2013,217137,-1164610,645839.0,89337.0,-66.38
24,(주)ES큐브,50120,2014,325908,171090,217137.0,-1164610.0,50.09

In [232]:
for i in range(0, len(qq1)-1):
    if qq1.loc[i,'회사명'] == qq1.loc[i+1,'회사명']:
        # 음수, 음수
        if qq1.iloc[i]["영업이익(연결)"] < 0 and qq1.iloc[i]["영업이익연결스"] < 0 :
            qq1.loc[i, "영업이익증가률연결"] = 11111111.11
        # 양수, 음수
        elif qq1.iloc[i]["영업이익(연결)"] > 0 and qq1.iloc[i]["영업이익연결스"] < 0:
            qq1.loc[i, "영업이익증가률연결"] = 11111111.11
        # 음수, 양수
        elif qq1.iloc[i]["영업이익(연결)"] < 0 and qq1.iloc[i]["영업이익연결스"] > 0:
            qq1.loc[i, "영업이익증가률연결"] = (((qq1.iloc[i]["영업이익(연결)"]-qq1.iloc[i]["영업이익연결스"]) / qq1.iloc[i]["영업이익연결스"])*100).round(2)
        # 양수, 양수
        elif qq1.iloc[i]["영업이익(연결)"] > 0 and qq1.iloc[i]["영업이익연결스"] > 0:
            qq1.loc[i, "영업이익증가률연결"] = (((qq1.iloc[i]["영업이익(연결)"]-qq1.iloc[i]["영업이익연결스"]) / qq1.iloc[i]["영업이익연결스"])*100).round(2)
        # 두개 중 하나라도 0이 있으면
        elif qq1.iloc[i]["영업이익(연결)"] == 0 or qq1.iloc[i]["영업이익연결스"] == 0:
            qq1.loc[i, "영업이익증가률연결"] = 0
        elif qq1.iloc[i]["영업이익연결스"] == 0:
            qq1.loc[i, "영업이익증가률개별"] = 11111111.11
        else:
            qq1.loc[i, "영업이익증가률연결"] = 1254789.63
    elif qq1.loc[i,'회사명'] != qq1.loc[i-1,'회사명']:
        # 음수, 음수
        if qq1.iloc[i]["영업이익(연결)"] < 0 and qq1.iloc[i]["영업이익연결스"] < 0 :
            qq1.loc[i, "영업이익증가률연결"] = 11111111.11
        # 양수, 음수
        elif qq1.iloc[i]["영업이익(연결)"] > 0 and qq1.iloc[i]["영업이익연결스"] < 0:
            qq1.loc[i, "영업이익증가률연결"] = 11111111.11
        # 음수, 양수
        elif qq1.iloc[i]["영업이익(연결)"] < 0 and qq1.iloc[i]["영업이익연결스"] > 0:
            qq1.loc[i, "영업이익증가률연결"] = (((qq1.iloc[i]["영업이익(연결)"]-qq1.iloc[i]["영업이익연결스"]) / qq1.iloc[i]["영업이익연결스"])*100).round(2)
        # 양수, 양수
        elif qq1.iloc[i]["영업이익(연결)"] > 0 and qq1.iloc[i]["영업이익연결스"] > 0:
            qq1.loc[i, "영업이익증가률연결"] = (((qq1.iloc[i]["영업이익(연결)"]-qq1.iloc[i]["영업이익연결스"]) / qq1.iloc[i]["영업이익연결스"])*100).round(2)
        # 두개 중 하나라도 0이 있으면
        elif qq1.iloc[i]["영업이익(연결)"] == 0:
            qq1.loc[i, "영업이익증가률연결"] = 0
        elif qq1.iloc[i]["영업이익연결스"] == 0:
            qq1.loc[i, "영업이익증가률개별"] = 11111111.11
        else:
            qq1.loc[i, "영업이익증가률연결"] = 1254789.63
    elif qq1.loc[i,'회사명'] == qq1.loc[i-1,'회사명']:
        # 음수, 음수
        if qq1.iloc[i]["영업이익(연결)"] < 0 and qq1.iloc[i]["영업이익연결스"] < 0 :
            qq1.loc[i, "영업이익증가률연결"] = 11111111.11
        # 양수, 음수
        elif qq1.iloc[i]["영업이익(연결)"] > 0 and qq1.iloc[i]["영업이익연결스"] < 0:
            qq1.loc[i, "영업이익증가률연결"] = 11111111.11
        # 음수, 양수
        elif qq1.iloc[i]["영업이익(연결)"] < 0 and qq1.iloc[i]["영업이익연결스"] > 0:
            qq1.loc[i, "영업이익증가률연결"] = (((qq1.iloc[i]["영업이익(연결)"]-qq1.iloc[i]["영업이익연결스"]) / qq1.iloc[i]["영업이익연결스"])*100).round(2)
        # 양수, 양수
        elif qq1.iloc[i]["영업이익(연결)"] > 0 and qq1.iloc[i]["영업이익연결스"] > 0:
            qq1.loc[i, "영업이익증가률연결"] = (((qq1.iloc[i]["영업이익(연결)"]-qq1.iloc[i]["영업이익연결스"]) / qq1.iloc[i]["영업이익연결스"])*100).round(2)
        # 두개 중 하나라도 0이 있으면
        elif qq1.iloc[i]["영업이익(연결)"] == 0:
            qq1.loc[i, "영업이익증가률연결"] = 0
        elif qq1.iloc[i]["영업이익연결스"] == 0:
            qq1.loc[i, "영업이익증가률개별"] = 11111111.11
        else:
            qq1.loc[i, "영업이익증가률연결"] = 1254789.63
        
qq1

,회사명,거래소코드,회계년도,영업이익(개별),영업이익(연결),영업이익개별스,영업이익연결스,영업이익증가률개별,영업이익증가률연결
0,(주)CMG제약,58820,2010,-7537070,-7537070,NaN,NaN,1254789.63,1254789.63
1,(주)CMG제약,58820,2011,714950,640282,-7537070.0,-7537070.0,11111111.11,11111111.11
2,(주)CMG제약,58820,2012,-4045140,-4205504,714950.0,640282.0,-665.79,-756.82
3,(주)CMG제약,58820,2013,822547,791250,-4045140.0,-4205504.0,11111111.11,11111111.11
4,(주)CMG제약,58820,2014,446017,442322,822547.0,791250.0,-45.78,-44.10
...,...,...,...,...,...,...,...,...,...
16498,흥아해운(주),3280,2015,16258441,21244278,15856524.0,18568741.0,2.53,14.41
16499,흥아해운(주),3280,2016,1154122,5895873,16258441.0,21244278.0,-92.90,-72.25
16500,흥아해운(주),3280,2017,-18649057,-13098624,1154122.0,5895873.0,-1715.87,-322.17
16501,흥아해운(주),3280,2018,-40598235,-37595967,-18649057.0,-13098624.0,11111111.11,11111111.11
16502,흥아해운(주),3280,2019,-14756167,-12364292,-40598235.0,-37595967.0,NaN,NaN

In [233]:
qq1[qq1['영업이익증가률개별']==0]

,회사명,거래소코드,회계년도,영업이익(개별),영업이익(연결),영업이익개별스,영업이익연결스,영업이익증가률개별,영업이익증가률연결
213,(주)고려시멘트,198440,2014,0,0,NaN,NaN,0.0,0.00
214,(주)고려시멘트,198440,2015,0,0,0.0,0.0,0.0,0.00
215,(주)고려시멘트,198440,2016,0,0,0.0,0.0,0.0,0.00
363,(주)국전약품,307750,2018,0,0,NaN,NaN,0.0,0.00
451,(주)나노,187790,2014,0,0,NaN,NaN,0.0,0.00
...,...,...,...,...,...,...,...,...,...
16203,헝셩그룹유한회사,900270,2018,0,34536637,0.0,39021752.0,0.0,-11.49
16255,현대무벡스(주),319400,2019,0,0,NaN,NaN,0.0,0.00
16472,휴마시스(주),205470,2014,0,0,NaN,NaN,0.0,0.00
16473,휴마시스(주),205470,2015,0,0,0.0,0.0,0.0,0.00
16474,휴마시스(주),205470,2016,0,0,0.0,0.0,0.0,0.00

In [234]:
qq1 = qq1.sort_values('회계년도')
qq1 = qq1.reset_index(drop=True)
qq1 = qq1.loc[1353:]
qq1 = qq1.sort_values(by=['회사명','회계년도'])
qq1 = qq1.reset_index(drop=True)
qq1

,회사명,거래소코드,회계년도,영업이익(개별),영업이익(연결),영업이익개별스,영업이익연결스,영업이익증가률개별,영업이익증가률연결
0,(주)CMG제약,58820,2011,714950,640282,-7537070.0,-7537070.0,11111111.11,11111111.11
1,(주)CMG제약,58820,2012,-4045140,-4205504,714950.0,640282.0,-665.79,-756.82
2,(주)CMG제약,58820,2013,822547,791250,-4045140.0,-4205504.0,11111111.11,11111111.11
3,(주)CMG제약,58820,2014,446017,442322,822547.0,791250.0,-45.78,-44.10
4,(주)CMG제약,58820,2015,-2570878,-2572169,446017.0,442322.0,-676.41,-681.52
...,...,...,...,...,...,...,...,...,...
15145,흥아해운(주),3280,2015,16258441,21244278,15856524.0,18568741.0,2.53,14.41
15146,흥아해운(주),3280,2016,1154122,5895873,16258441.0,21244278.0,-92.90,-72.25
15147,흥아해운(주),3280,2017,-18649057,-13098624,1154122.0,5895873.0,-1715.87,-322.17
15148,흥아해운(주),3280,2018,-40598235,-37595967,-18649057.0,-13098624.0,11111111.11,11111111.11
15149,흥아해운(주),3280,2019,-14756167,-12364292,-40598235.0,-37595967.0,NaN,NaN

In [238]:
qq2 = pd.concat([df['정상영업이익증가율'],qq1[['영업이익증가률개별','영업이익증가률연결']]],axis=1)
qq2 = qq2.fillna(11111111.11)

In [239]:
for i in range(len(qq2)):
    if qq2.loc[i,'정상영업이익증가율'] == 0:
        if qq2.loc[i,'영업이익증가률개별'] != 11111111.11:
            if qq2.loc[i,'영업이익증가률연결'] != 11111111.11:
                qq2.loc[i,'정상영업이익증가율'] = qq2.loc[i,'영업이익증가률연결']
            else:
                qq2.loc[i,'정상영업이익증가율'] = qq2.loc[i,'영업이익증가률개별']
        else:
            if qq2.loc[i,'영업이익증가률연결'] != 11111111.11:
                qq2.loc[i,'정상영업이익증가율'] = qq2.loc[i,'영업이익증가률연결']
            else:
                qq2.loc[i,'정상영업이익증가율'] = 1254789.63
        if qq2.loc[i,'영업이익증가률연결'] == 0:
            qq2.loc[i,'정상영업이익증가율'] = qq2.loc[i,'영업이익증가률개별']
        if qq2.loc[i,'영업이익증가률연결'] == 11111111.11:
            qq2.loc[i,'정상영업이익증가율'] = 11111111.11
    if qq2.loc[i,'정상영업이익증가율'] == 11111111.11:
        if qq2.loc[i,'영업이익증가률연결'] != 11111111.11:
            if qq2.loc[i,'영업이익증가률개별'] != 11111111.11:
                qq2.loc[i,'정상영업이익증가율'] = qq2.loc[i,'영업이익증가률연결']
            else:
                qq2.loc[i,'정상영업이익증가율'] = qq2.loc[i,'영업이익증가률연결']
        if qq2.loc[i,'영업이익증가률연결'] == 11111111.11:
            if qq2.loc[i,'영업이익증가률개별'] != 11111111.11:
                qq2.loc[i,'정상영업이익증가율'] = qq2.loc[i,'영업이익증가률개별']
            else:
                qq2.loc[i,'정상영업이익증가율'] = 1254789.63
        
qq2

        정상영업이익증가율    영업이익증가률개별    영업이익증가률연결
0      1254789.63  11111111.11  11111111.11
1         -756.82      -665.79      -756.82
2      1254789.63  11111111.11  11111111.11
3          -46.64       -45.78       -44.10
4         -681.52      -676.41      -681.52
...           ...          ...          ...
15145      -42.68         2.53        14.41
15146     -263.29       -92.90       -72.25
15147     -322.17     -1715.87      -322.17
15148  1254789.63  11111111.11  11111111.11
15149  1254789.63  11111111.11  11111111.11

[15150 rows x 3 columns]

In [242]:
qq2[qq2['정상영업이익증가율']==1254789.63]

        정상영업이익증가율    영업이익증가률개별    영업이익증가률연결
0      1254789.63  11111111.11  11111111.11
2      1254789.63  11111111.11  11111111.11
5      1254789.63  11111111.11  11111111.11
9      1254789.63  11111111.11  11111111.11
10     1254789.63  11111111.11  11111111.11
...           ...          ...          ...
15116  1254789.63  11111111.11  11111111.11
15120  1254789.63  11111111.11  11111111.11
15142  1254789.63  11111111.11  11111111.11
15148  1254789.63  11111111.11  11111111.11
15149  1254789.63  11111111.11  11111111.11

[2019 rows x 3 columns]

In [240]:
qq2.to_csv('정상영업이익증가율최종.csv',encoding='cp949')