In [1]:
import pandas as pd

df = pd.read_csv('회사상장일.csv',encoding='cp949')
df

            회사명  거래소코드     회계년도         상장일         설립일
0      (주)CMG제약  58820  2011/12  2001/08/31  2001/08/01
1      (주)CMG제약  58820  2012/12  2001/08/31  2001/08/01
2      (주)CMG제약  58820  2013/12  2001/08/31  2001/08/01
3      (주)CMG제약  58820  2014/12  2001/08/31  2001/08/01
4      (주)CMG제약  58820  2015/12  2001/08/31  2001/08/01
...         ...    ...      ...         ...         ...
15145   흥아해운(주)   3280  2015/12  1976/06/29  1961/12/08
15146   흥아해운(주)   3280  2016/12  1976/06/29  1961/12/08
15147   흥아해운(주)   3280  2017/12  1976/06/29  1961/12/08
15148   흥아해운(주)   3280  2018/12  1976/06/29  1961/12/08
15149   흥아해운(주)   3280  2019/12  1976/06/29  1961/12/08

[15150 rows x 5 columns]

In [2]:
df = df.drop_duplicates('회사명')
df

            회사명   거래소코드     회계년도         상장일         설립일
0      (주)CMG제약   58820  2011/12  2001/08/31  2001/08/01
9      (주)DB하이텍     990  2011/12  1975/12/12  1953/04/28
18      (주)ES큐브   50120  2011/12  2002/04/25  1977/06/20
27     (주)HJ중공업   97230  2011/12  2007/08/31  2007/08/03
36     (주)MH에탄올   23150  2011/12  1996/12/24  1978/07/04
...         ...     ...      ...         ...         ...
15112   휴림로봇(주)   90710  2011/12  2006/12/05  1998/11/29
15121   휴마시스(주)  205470  2014/12  2014/12/01  2014/08/29
15127     휴젤(주)  145020  2015/12  2015/12/24  2001/11/22
15132   흥구석유(주)   24060  2011/12  1994/12/07  1966/12/16
15141   흥아해운(주)    3280  2011/12  1976/06/29  1961/12/08

[2023 rows x 5 columns]

In [3]:
from operator import index


df.to_csv('회사상장.csv',encoding='cp949',index=False)